package com.rmi.applicationEntry.adfbc.views.readOnlyVO;

import java.math.BigDecimal;

import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 01 21:57:00 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyTasksViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EsiBatchId,
        BatchStatus,
        BatchDate,
        BatchName,
        NoOfSeafarer,
        Region,
        CraCount,
        CraSentCount,
        OrderSource,
        WorkOrderNo,
        WfStatus,
        OeHeaderId,
        ExpeditedProcessingMytask,
        finalCra;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return MyTasksViewRowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return MyTasksViewRowImpl.AttributesEnum.firstIndex() +
                   MyTasksViewRowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = MyTasksViewRowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ESIBATCHID = AttributesEnum.EsiBatchId.index();
    public static final int BATCHSTATUS = AttributesEnum.BatchStatus.index();
    public static final int BATCHDATE = AttributesEnum.BatchDate.index();
    public static final int BATCHNAME = AttributesEnum.BatchName.index();
    public static final int NOOFSEAFARER = AttributesEnum.NoOfSeafarer.index();
    public static final int REGION = AttributesEnum.Region.index();
    public static final int CRACOUNT = AttributesEnum.CraCount.index();
    public static final int CRASENTCOUNT = AttributesEnum.CraSentCount.index();
    public static final int ORDERSOURCE = AttributesEnum.OrderSource.index();
    public static final int WORKORDERNO = AttributesEnum.WorkOrderNo.index();
    public static final int WFSTATUS = AttributesEnum.WfStatus.index();
    public static final int OEHEADERID = AttributesEnum.OeHeaderId.index();
    public static final int EXPEDITEDPROCESSINGMYTASK = AttributesEnum.ExpeditedProcessingMytask.index();
    public static final int FINALCRA = AttributesEnum.finalCra.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MyTasksViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EsiBatchId.
     * @return the EsiBatchId
     */
    public Integer getEsiBatchId() {
        return (Integer) getAttributeInternal(ESIBATCHID);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchStatus.
     * @return the BatchStatus
     */
    public String getBatchStatus() {
        return (String) getAttributeInternal(BATCHSTATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchDate.
     * @return the BatchDate
     */
    public Date getBatchDate() {
        return (Date) getAttributeInternal(BATCHDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchName.
     * @return the BatchName
     */
    public String getBatchName() {
        return (String) getAttributeInternal(BATCHNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute NoOfSeafarer.
     * @return the NoOfSeafarer
     */
    public Integer getNoOfSeafarer() {
        return (Integer) getAttributeInternal(NOOFSEAFARER);
    }

    /**
     * Gets the attribute value for the calculated attribute Region.
     * @return the Region
     */
    public String getRegion() {
        return (String) getAttributeInternal(REGION);
    }

    /**
     * Gets the attribute value for the calculated attribute CraCount.
     * @return the CraCount
     */
    public Integer getCraCount() {
        return (Integer) getAttributeInternal(CRACOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute CraSentCount.
     * @return the CraSentCount
     */
    public Integer getCraSentCount() {
        return (Integer) getAttributeInternal(CRASENTCOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderSource.
     * @return the OrderSource
     */
    public String getOrderSource() {
        return (String) getAttributeInternal(ORDERSOURCE);
    }

    /**
     * Gets the attribute value for the calculated attribute WorkOrderNo.
     * @return the WorkOrderNo
     */
    public Integer getWorkOrderNo() {
        return (Integer) getAttributeInternal(WORKORDERNO);
    }

    /**
     * Gets the attribute value for the calculated attribute WfStatus.
     * @return the WfStatus
     */
    public String getWfStatus() {
        return (String) getAttributeInternal(WFSTATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute OeHeaderId.
     * @return the OeHeaderId
     */
    public Integer getOeHeaderId() {
        return (Integer) getAttributeInternal(OEHEADERID);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpeditedProcessingMytask.
     * @return the ExpeditedProcessingMytask
     */
    public Boolean getExpeditedProcessingMytask() {
        return (Boolean) getAttributeInternal(EXPEDITEDPROCESSINGMYTASK);
    }

    /**
     * Gets the attribute value for the calculated attribute finalCra.
     * @return the finalCra
     */
    public Integer getfinalCra() {
        Integer fcount = 0;
        Integer crasentcount = getCraSentCount();
        Integer craCount = getCraCount();
        if(crasentcount  == 0)
        {
            if(craCount > 0)
            {
               fcount = 1; 
                }
            else
            {
              fcount = 0;  
                }
            }
        else
        {
         fcount = -1;   
            }
        return fcount;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute finalCra.
     * @param value value to set the  finalCra
     */
    public void setfinalCra(Integer value) {
        setAttributeInternal(FINALCRA, value);
    }
}

