package com.rmi.applicationEntry.adfbc.views.readOnlyVO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 04 17:18:33 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchesPendingMtcViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EsiBatchId,
        BatchStatus,
        BatchDate,
        BatchName,
        NoOfSeafarer,
        Region,
        RegionId,
        WorkOrderNo,
        OrderType,
        ExpeditedProcessing,
        CraCount,
        CraSentCount,
        finalCra;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ESIBATCHID = AttributesEnum.EsiBatchId.index();
    public static final int BATCHSTATUS = AttributesEnum.BatchStatus.index();
    public static final int BATCHDATE = AttributesEnum.BatchDate.index();
    public static final int BATCHNAME = AttributesEnum.BatchName.index();
    public static final int NOOFSEAFARER = AttributesEnum.NoOfSeafarer.index();
    public static final int REGION = AttributesEnum.Region.index();
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int WORKORDERNO = AttributesEnum.WorkOrderNo.index();
    public static final int ORDERTYPE = AttributesEnum.OrderType.index();
    public static final int EXPEDITEDPROCESSING = AttributesEnum.ExpeditedProcessing.index();
    public static final int CRACOUNT = AttributesEnum.CraCount.index();
    public static final int CRASENTCOUNT = AttributesEnum.CraSentCount.index();
    public static final int FINALCRA = AttributesEnum.finalCra.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BatchesPendingMtcViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EsiBatchId.
     * @return the EsiBatchId
     */
    public BigDecimal getEsiBatchId() {
        return (BigDecimal) getAttributeInternal(ESIBATCHID);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchStatus.
     * @return the BatchStatus
     */
    public String getBatchStatus() {
        return (String) getAttributeInternal(BATCHSTATUS);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchDate.
     * @return the BatchDate
     */
    public Timestamp getBatchDate() {
        return (Timestamp) getAttributeInternal(BATCHDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute BatchName.
     * @return the BatchName
     */
    public String getBatchName() {
        return (String) getAttributeInternal(BATCHNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute NoOfSeafarer.
     * @return the NoOfSeafarer
     */
    public BigDecimal getNoOfSeafarer() {
        return (BigDecimal) getAttributeInternal(NOOFSEAFARER);
    }

    /**
     * Gets the attribute value for the calculated attribute Region.
     * @return the Region
     */
    public String getRegion() {
        return (String) getAttributeInternal(REGION);
    }

    /**
     * Gets the attribute value for the calculated attribute RegionId.
     * @return the RegionId
     */
    public BigDecimal getRegionId() {
        return (BigDecimal) getAttributeInternal(REGIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute WorkOrderNo.
     * @return the WorkOrderNo
     */
    public BigDecimal getWorkOrderNo() {
        return (BigDecimal) getAttributeInternal(WORKORDERNO);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderType.
     * @return the OrderType
     */
    public String getOrderType() {
        return (String) getAttributeInternal(ORDERTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpeditedProcessing.
     * @return the ExpeditedProcessing
     */
    public String getExpeditedProcessing() {
        return (String) getAttributeInternal(EXPEDITEDPROCESSING);
    }

    /**
     * Gets the attribute value for the calculated attribute CraCount.
     * @return the CraCount
     */
    public Integer getCraCount() {
        return (Integer) getAttributeInternal(CRACOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute CraSentCount.
     * @return the CraSentCount
     */
    public Integer getCraSentCount() {
        return (Integer) getAttributeInternal(CRASENTCOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute finalCra.
     * @return the finalCra
     */
    public Integer getfinalCra() {
        Integer fcount = 0;
        Integer crasentcount = getCraSentCount();
        Integer craCount = getCraCount();
        if(crasentcount  == 0)
        {
            if(craCount > 0)
            {
               fcount = 1; 
                }
            else
            {
              fcount = 0;  
                }
            }
        else
        {
         fcount = -1;   
            }
        return fcount;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute finalCra.
     * @param value value to set the  finalCra
     */
    public void setfinalCra(Integer value) {
        setAttributeInternal(FINALCRA, value);
    }
}

