package com.rmi.applicationEntry.adfbc.entities;

import com.rmi.applicationEntry.adfbc.extensions.CustomEntity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 01 17:24:32 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BatchIfaceImpl extends CustomEntity {
    /**
     * Add locking logic here.
     */
    public void lock() {
//        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        System.out.println("UserId in ApplicationEntry.RmiBatchIface doDML :: "+ADFContext.getCurrent().getSessionScope().get("UserId"));
        System.out.println("Role in ApplicationEntry.RmiBatchIface doDML :: "+ADFContext.getCurrent().getSessionScope().get("RoleName"));
        System.out.println("Operation in ApplicationEntry.RmiBatchIface doDML :: "+((operation == 1) ? "INSERT" : "UPDATE"));
        System.out.println("Source in ApplicationEntry.RmiBatchIface doDML :: "+e.getSource().getClass().getName());
        super.doDML(operation, e);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EsiBatchId,
        BillToCustAccountId,
        BillToSiteUseId,
        BillToOrgContactId,
        ShipToCustAccountId,
        ShipToSiteUseId,
        ShipToOrgContactId,
        BatchDate,
        BatchName,
        BatchStatus,
        OeHeaderId,
        PurchaseOrderNumber,
        VesselNames,
        Notes,
        BatchSubmittedDate,
        BatchReturnedDate,
        BatchResubmittedDate,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        BatchSubmittedBy,
        ExpeditedProcessing,
        DeliverToSiteUseId,
        DeliverToCustAccountId,
        BatchAssignedToRegion,
        InvoiceAgentEmailId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return BatchIfaceImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return BatchIfaceImpl.AttributesEnum.firstIndex() + BatchIfaceImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = BatchIfaceImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ESIBATCHID = AttributesEnum.EsiBatchId.index();
    public static final int BILLTOCUSTACCOUNTID = AttributesEnum.BillToCustAccountId.index();
    public static final int BILLTOSITEUSEID = AttributesEnum.BillToSiteUseId.index();
    public static final int BILLTOORGCONTACTID = AttributesEnum.BillToOrgContactId.index();
    public static final int SHIPTOCUSTACCOUNTID = AttributesEnum.ShipToCustAccountId.index();
    public static final int SHIPTOSITEUSEID = AttributesEnum.ShipToSiteUseId.index();
    public static final int SHIPTOORGCONTACTID = AttributesEnum.ShipToOrgContactId.index();
    public static final int BATCHDATE = AttributesEnum.BatchDate.index();
    public static final int BATCHNAME = AttributesEnum.BatchName.index();
    public static final int BATCHSTATUS = AttributesEnum.BatchStatus.index();
    public static final int OEHEADERID = AttributesEnum.OeHeaderId.index();
    public static final int PURCHASEORDERNUMBER = AttributesEnum.PurchaseOrderNumber.index();
    public static final int VESSELNAMES = AttributesEnum.VesselNames.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int BATCHSUBMITTEDDATE = AttributesEnum.BatchSubmittedDate.index();
    public static final int BATCHRETURNEDDATE = AttributesEnum.BatchReturnedDate.index();
    public static final int BATCHRESUBMITTEDDATE = AttributesEnum.BatchResubmittedDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int BATCHSUBMITTEDBY = AttributesEnum.BatchSubmittedBy.index();
    public static final int EXPEDITEDPROCESSING = AttributesEnum.ExpeditedProcessing.index();
    public static final int DELIVERTOSITEUSEID = AttributesEnum.DeliverToSiteUseId.index();
    public static final int DELIVERTOCUSTACCOUNTID = AttributesEnum.DeliverToCustAccountId.index();
    public static final int BATCHASSIGNEDTOREGION = AttributesEnum.BatchAssignedToRegion.index();
    public static final int INVOICEAGENTEMAILID = AttributesEnum.InvoiceAgentEmailId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BatchIfaceImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.rmi.applicationEntry.adfbc.entities.BatchIface");
    }


    /**
     * Gets the attribute value for EsiBatchId, using the alias name EsiBatchId.
     * @return the value of EsiBatchId
     */
    public Number getEsiBatchId() {
        return (Number) getAttributeInternal(ESIBATCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EsiBatchId.
     * @param value value to set the EsiBatchId
     */
    public void setEsiBatchId(Number value) {
        setAttributeInternal(ESIBATCHID, value);
    }

    /**
     * Gets the attribute value for BillToCustAccountId, using the alias name BillToCustAccountId.
     * @return the value of BillToCustAccountId
     */
    public Integer getBillToCustAccountId() {
        return (Integer) getAttributeInternal(BILLTOCUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToCustAccountId.
     * @param value value to set the BillToCustAccountId
     */
    public void setBillToCustAccountId(Integer value) {
        setAttributeInternal(BILLTOCUSTACCOUNTID, value);
    }

    /**
     * Gets the attribute value for BillToSiteUseId, using the alias name BillToSiteUseId.
     * @return the value of BillToSiteUseId
     */
    public Integer getBillToSiteUseId() {
        return (Integer) getAttributeInternal(BILLTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToSiteUseId.
     * @param value value to set the BillToSiteUseId
     */
    public void setBillToSiteUseId(Integer value) {
        setAttributeInternal(BILLTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for BillToOrgContactId, using the alias name BillToOrgContactId.
     * @return the value of BillToOrgContactId
     */
    public BigDecimal getBillToOrgContactId() {
        return (BigDecimal) getAttributeInternal(BILLTOORGCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillToOrgContactId.
     * @param value value to set the BillToOrgContactId
     */
    public void setBillToOrgContactId(BigDecimal value) {
        setAttributeInternal(BILLTOORGCONTACTID, value);
    }

    /**
     * Gets the attribute value for ShipToCustAccountId, using the alias name ShipToCustAccountId.
     * @return the value of ShipToCustAccountId
     */
    public Integer getShipToCustAccountId() {
        return (Integer) getAttributeInternal(SHIPTOCUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToCustAccountId.
     * @param value value to set the ShipToCustAccountId
     */
    public void setShipToCustAccountId(Integer value) {
        setAttributeInternal(SHIPTOCUSTACCOUNTID, value);
    }

    /**
     * Gets the attribute value for ShipToSiteUseId, using the alias name ShipToSiteUseId.
     * @return the value of ShipToSiteUseId
     */
    public Integer getShipToSiteUseId() {
        return (Integer) getAttributeInternal(SHIPTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToSiteUseId.
     * @param value value to set the ShipToSiteUseId
     */
    public void setShipToSiteUseId(Integer value) {
        setAttributeInternal(SHIPTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for ShipToOrgContactId, using the alias name ShipToOrgContactId.
     * @return the value of ShipToOrgContactId
     */
    public BigDecimal getShipToOrgContactId() {
        return (BigDecimal) getAttributeInternal(SHIPTOORGCONTACTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToOrgContactId.
     * @param value value to set the ShipToOrgContactId
     */
    public void setShipToOrgContactId(BigDecimal value) {
        setAttributeInternal(SHIPTOORGCONTACTID, value);
    }

    /**
     * Gets the attribute value for BatchDate, using the alias name BatchDate.
     * @return the value of BatchDate
     */
    public Date getBatchDate() {
        return (Date) getAttributeInternal(BATCHDATE);
    }

    /**
     * Gets the attribute value for BatchName, using the alias name BatchName.
     * @return the value of BatchName
     */
    public String getBatchName() {
        return (String) getAttributeInternal(BATCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchName.
     * @param value value to set the BatchName
     */
    public void setBatchName(String value) {
        setAttributeInternal(BATCHNAME, value);
    }

    /**
     * Gets the attribute value for BatchStatus, using the alias name BatchStatus.
     * @return the value of BatchStatus
     */
    public String getBatchStatus() {
        return (String) getAttributeInternal(BATCHSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchStatus.
     * @param value value to set the BatchStatus
     */
    public void setBatchStatus(String value) {
        setAttributeInternal(BATCHSTATUS, value);
    }

    /**
     * Gets the attribute value for OeHeaderId, using the alias name OeHeaderId.
     * @return the value of OeHeaderId
     */
    public Integer getOeHeaderId() {
        return (Integer) getAttributeInternal(OEHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OeHeaderId.
     * @param value value to set the OeHeaderId
     */
    public void setOeHeaderId(Integer value) {
        setAttributeInternal(OEHEADERID, value);
    }

    /**
     * Gets the attribute value for PurchaseOrderNumber, using the alias name PurchaseOrderNumber.
     * @return the value of PurchaseOrderNumber
     */
    public String getPurchaseOrderNumber() {
        return (String) getAttributeInternal(PURCHASEORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchaseOrderNumber.
     * @param value value to set the PurchaseOrderNumber
     */
    public void setPurchaseOrderNumber(String value) {
        setAttributeInternal(PURCHASEORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for VesselNames, using the alias name VesselNames.
     * @return the value of VesselNames
     */
    public String getVesselNames() {
        return (String) getAttributeInternal(VESSELNAMES);
    }

    /**
     * Sets <code>value</code> as the attribute value for VesselNames.
     * @param value value to set the VesselNames
     */
    public void setVesselNames(String value) {
        setAttributeInternal(VESSELNAMES, value);
    }

    /**
     * Gets the attribute value for Notes, using the alias name Notes.
     * @return the value of Notes
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Notes.
     * @param value value to set the Notes
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for BatchSubmittedDate, using the alias name BatchSubmittedDate.
     * @return the value of BatchSubmittedDate
     */
    public Date getBatchSubmittedDate() {
        return (Date) getAttributeInternal(BATCHSUBMITTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchSubmittedDate.
     * @param value value to set the BatchSubmittedDate
     */
    public void setBatchSubmittedDate(Date value) {
        setAttributeInternal(BATCHSUBMITTEDDATE, value);
    }

    /**
     * Gets the attribute value for BatchReturnedDate, using the alias name BatchReturnedDate.
     * @return the value of BatchReturnedDate
     */
    public Timestamp getBatchReturnedDate() {
        return (Timestamp) getAttributeInternal(BATCHRETURNEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchReturnedDate.
     * @param value value to set the BatchReturnedDate
     */
    public void setBatchReturnedDate(Timestamp value) {
        setAttributeInternal(BATCHRETURNEDDATE, value);
    }

    /**
     * Gets the attribute value for BatchResubmittedDate, using the alias name BatchResubmittedDate.
     * @return the value of BatchResubmittedDate
     */
    public Timestamp getBatchResubmittedDate() {
        return (Timestamp) getAttributeInternal(BATCHRESUBMITTEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchResubmittedDate.
     * @param value value to set the BatchResubmittedDate
     */
    public void setBatchResubmittedDate(Timestamp value) {
        setAttributeInternal(BATCHRESUBMITTEDDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public BigDecimal getLastUpdatedBy() {
        return (BigDecimal) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(BigDecimal value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public BigDecimal getLastUpdateLogin() {
        return (BigDecimal) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(BigDecimal value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for BatchSubmittedBy, using the alias name BatchSubmittedBy.
     * @return the value of BatchSubmittedBy
     */
    public Integer getBatchSubmittedBy() {
        return (Integer) getAttributeInternal(BATCHSUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchSubmittedBy.
     * @param value value to set the BatchSubmittedBy
     */
    public void setBatchSubmittedBy(Integer value) {
        setAttributeInternal(BATCHSUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for ExpeditedProcessing, using the alias name ExpeditedProcessing.
     * @return the value of ExpeditedProcessing
     */
    public String getExpeditedProcessing() {
        return (String) getAttributeInternal(EXPEDITEDPROCESSING);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpeditedProcessing.
     * @param value value to set the ExpeditedProcessing
     */
    public void setExpeditedProcessing(String value) {
        setAttributeInternal(EXPEDITEDPROCESSING, value);
    }

    /**
     * Gets the attribute value for DeliverToSiteUseId, using the alias name DeliverToSiteUseId.
     * @return the value of DeliverToSiteUseId
     */
    public Integer getDeliverToSiteUseId() {
        return (Integer) getAttributeInternal(DELIVERTOSITEUSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliverToSiteUseId.
     * @param value value to set the DeliverToSiteUseId
     */
    public void setDeliverToSiteUseId(Integer value) {
        setAttributeInternal(DELIVERTOSITEUSEID, value);
    }

    /**
     * Gets the attribute value for DeliverToCustAccountId, using the alias name DeliverToCustAccountId.
     * @return the value of DeliverToCustAccountId
     */
    public Integer getDeliverToCustAccountId() {
        return (Integer) getAttributeInternal(DELIVERTOCUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliverToCustAccountId.
     * @param value value to set the DeliverToCustAccountId
     */
    public void setDeliverToCustAccountId(Integer value) {
        setAttributeInternal(DELIVERTOCUSTACCOUNTID, value);
    }


    /**
     * Gets the attribute value for BatchAssignedToRegion, using the alias name BatchAssignedToRegion.
     * @return the value of BatchAssignedToRegion
     */
    public Integer getBatchAssignedToRegion() {
        return (Integer) getAttributeInternal(BATCHASSIGNEDTOREGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchAssignedToRegion.
     * @param value value to set the BatchAssignedToRegion
     */
    public void setBatchAssignedToRegion(Integer value) {
        setAttributeInternal(BATCHASSIGNEDTOREGION, value);
    }


    /**
     * Gets the attribute value for InvoiceAgentEmailId, using the alias name InvoiceAgentEmailId.
     * @return the value of InvoiceAgentEmailId
     */
    public String getInvoiceAgentEmailId() {
        return (String) getAttributeInternal(INVOICEAGENTEMAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceAgentEmailId.
     * @param value value to set the InvoiceAgentEmailId
     */
    public void setInvoiceAgentEmailId(String value) {
        setAttributeInternal(INVOICEAGENTEMAILID, value);
    }

    /**
     * @param esiBatchId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number esiBatchId) {
        return new Key(new Object[] { esiBatchId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    
    }
}

