SELECT *
FROM wc_screening_request a
WHERE 1 = 1
AND NOT EXISTS (SELECT 1
FROM xwrl.xwrl_party_master b
WHERE b.WC_SCREENING_REQUEST_ID = a.WC_SCREENING_REQUEST_ID)
AND NOT EXISTS (SELECT 1
FROM xwrl.xwrl_party_alias b
WHERE b.WC_SCREENING_REQUEST_ID = a.WC_SCREENING_REQUEST_ID)