SELECT A.SID,A.SERIAL#,A.OSUSER,A.PROCESS,C.OBJECT_NAME
  FROM V$SESSION A,V$LOCKED_OBJECT B,DBA_OBJECTS C
 WHERE A.SID = B.SESSION_ID
   AND B.OBJECT_ID = C.OBJECT_ID
   AND C.OBJECT_NAME = 'XWRL_WC_CONTENTS'
   ;
   
   select *
   from V$SESSION
   where sid = 1978   
   ;

   
   ALTER SYSTEM KILL SESSION '1248,38350'; 