package oracle.apps.xwrl.model.view;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 06 16:00:55 EDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XwrlRequestEntityColumnsViewRowImpl extends ViewRowImpl
{


  public static final int ENTITY_XWRLREQUESTENTITYCOLUMNS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
    public enum AttributesEnum {
    Id,
    RequestId,
    Listsubkey,
    Listrecordtype,
    Listrecordorigin,
    Custid,
    Custsubid,
    Registrationnumber,
    Entityname,
    Nametype,
    Namequality,
    Primaryname,
    Originalscriptname,
    Aliasisacronym,
    Address1,
    Address2,
    Address3,
    Address4,
    City,
    State,
    Postalcode,
    Addresscountrycode,
    Registrationcountrycode,
    Operatingcountrycodes,
    Profilehyperlink,
    Riskscore,
    Dataconfidencescore,
    Dataconfidencecomment,
    Customstring1,
    Customstring2,
    Customstring3,
    Customstring4,
    Customstring5,
    Customstring6,
    Customstring7,
    Customstring8,
    Customstring9,
    Customstring10,
    Customstring11,
    Customstring12,
    Customstring13,
    Customstring14,
    Customstring15,
    Customstring16,
    Customstring17,
    Customstring18,
    Customstring19,
    Customstring20,
    Customstring21,
    Customstring22,
    Customstring23,
    Customstring24,
    Customstring25,
    Customstring26,
    Customstring27,
    Customstring28,
    Customstring29,
    Customstring30,
    Customstring31,
    Customstring32,
    Customstring33,
    Customstring34,
    Customstring35,
    Customstring36,
    Customstring37,
    Customstring38,
    Customstring39,
    Customstring40,
    Customdate1,
    Customdate2,
    Customdate3,
    Customdate4,
    Customdate5,
    Customnumber1,
    Customnumber2,
    Customnumber3,
    Customnumber4,
    Customnumber5,
    LastUpdateDate,
    LastUpdatedBy,
    CreationDate,
    CreatedBy,
    LastUpdateLogin,
    CaseCountryLOV1,
    FndUsersAllLov1,
    CaseRestrictedCityLOV1;
    static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int ID = AttributesEnum.Id.index();
  public static final int REQUESTID = AttributesEnum.RequestId.index();
  public static final int LISTSUBKEY = AttributesEnum.Listsubkey.index();
  public static final int LISTRECORDTYPE = AttributesEnum.Listrecordtype.index();
  public static final int LISTRECORDORIGIN = AttributesEnum.Listrecordorigin.index();
  public static final int CUSTID = AttributesEnum.Custid.index();
  public static final int CUSTSUBID = AttributesEnum.Custsubid.index();
  public static final int REGISTRATIONNUMBER = AttributesEnum.Registrationnumber.index();
  public static final int ENTITYNAME = AttributesEnum.Entityname.index();
  public static final int NAMETYPE = AttributesEnum.Nametype.index();
  public static final int NAMEQUALITY = AttributesEnum.Namequality.index();
  public static final int PRIMARYNAME = AttributesEnum.Primaryname.index();
  public static final int ORIGINALSCRIPTNAME = AttributesEnum.Originalscriptname.index();
  public static final int ALIASISACRONYM = AttributesEnum.Aliasisacronym.index();
  public static final int ADDRESS1 = AttributesEnum.Address1.index();
  public static final int ADDRESS2 = AttributesEnum.Address2.index();
  public static final int ADDRESS3 = AttributesEnum.Address3.index();
  public static final int ADDRESS4 = AttributesEnum.Address4.index();
  public static final int CITY = AttributesEnum.City.index();
  public static final int STATE = AttributesEnum.State.index();
  public static final int POSTALCODE = AttributesEnum.Postalcode.index();
  public static final int ADDRESSCOUNTRYCODE = AttributesEnum.Addresscountrycode.index();
  public static final int REGISTRATIONCOUNTRYCODE = AttributesEnum.Registrationcountrycode.index();
  public static final int OPERATINGCOUNTRYCODES = AttributesEnum.Operatingcountrycodes.index();
  public static final int PROFILEHYPERLINK = AttributesEnum.Profilehyperlink.index();
  public static final int RISKSCORE = AttributesEnum.Riskscore.index();
  public static final int DATACONFIDENCESCORE = AttributesEnum.Dataconfidencescore.index();
  public static final int DATACONFIDENCECOMMENT = AttributesEnum.Dataconfidencecomment.index();
  public static final int CUSTOMSTRING1 = AttributesEnum.Customstring1.index();
  public static final int CUSTOMSTRING2 = AttributesEnum.Customstring2.index();
  public static final int CUSTOMSTRING3 = AttributesEnum.Customstring3.index();
  public static final int CUSTOMSTRING4 = AttributesEnum.Customstring4.index();
  public static final int CUSTOMSTRING5 = AttributesEnum.Customstring5.index();
  public static final int CUSTOMSTRING6 = AttributesEnum.Customstring6.index();
  public static final int CUSTOMSTRING7 = AttributesEnum.Customstring7.index();
  public static final int CUSTOMSTRING8 = AttributesEnum.Customstring8.index();
  public static final int CUSTOMSTRING9 = AttributesEnum.Customstring9.index();
  public static final int CUSTOMSTRING10 = AttributesEnum.Customstring10.index();
  public static final int CUSTOMSTRING11 = AttributesEnum.Customstring11.index();
  public static final int CUSTOMSTRING12 = AttributesEnum.Customstring12.index();
  public static final int CUSTOMSTRING13 = AttributesEnum.Customstring13.index();
  public static final int CUSTOMSTRING14 = AttributesEnum.Customstring14.index();
  public static final int CUSTOMSTRING15 = AttributesEnum.Customstring15.index();
  public static final int CUSTOMSTRING16 = AttributesEnum.Customstring16.index();
  public static final int CUSTOMSTRING17 = AttributesEnum.Customstring17.index();
  public static final int CUSTOMSTRING18 = AttributesEnum.Customstring18.index();
  public static final int CUSTOMSTRING19 = AttributesEnum.Customstring19.index();
  public static final int CUSTOMSTRING20 = AttributesEnum.Customstring20.index();
  public static final int CUSTOMSTRING21 = AttributesEnum.Customstring21.index();
  public static final int CUSTOMSTRING22 = AttributesEnum.Customstring22.index();
  public static final int CUSTOMSTRING23 = AttributesEnum.Customstring23.index();
  public static final int CUSTOMSTRING24 = AttributesEnum.Customstring24.index();
  public static final int CUSTOMSTRING25 = AttributesEnum.Customstring25.index();
  public static final int CUSTOMSTRING26 = AttributesEnum.Customstring26.index();
  public static final int CUSTOMSTRING27 = AttributesEnum.Customstring27.index();
  public static final int CUSTOMSTRING28 = AttributesEnum.Customstring28.index();
  public static final int CUSTOMSTRING29 = AttributesEnum.Customstring29.index();
  public static final int CUSTOMSTRING30 = AttributesEnum.Customstring30.index();
  public static final int CUSTOMSTRING31 = AttributesEnum.Customstring31.index();
  public static final int CUSTOMSTRING32 = AttributesEnum.Customstring32.index();
  public static final int CUSTOMSTRING33 = AttributesEnum.Customstring33.index();
  public static final int CUSTOMSTRING34 = AttributesEnum.Customstring34.index();
  public static final int CUSTOMSTRING35 = AttributesEnum.Customstring35.index();
  public static final int CUSTOMSTRING36 = AttributesEnum.Customstring36.index();
  public static final int CUSTOMSTRING37 = AttributesEnum.Customstring37.index();
  public static final int CUSTOMSTRING38 = AttributesEnum.Customstring38.index();
  public static final int CUSTOMSTRING39 = AttributesEnum.Customstring39.index();
  public static final int CUSTOMSTRING40 = AttributesEnum.Customstring40.index();
  public static final int CUSTOMDATE1 = AttributesEnum.Customdate1.index();
  public static final int CUSTOMDATE2 = AttributesEnum.Customdate2.index();
  public static final int CUSTOMDATE3 = AttributesEnum.Customdate3.index();
  public static final int CUSTOMDATE4 = AttributesEnum.Customdate4.index();
  public static final int CUSTOMDATE5 = AttributesEnum.Customdate5.index();
  public static final int CUSTOMNUMBER1 = AttributesEnum.Customnumber1.index();
  public static final int CUSTOMNUMBER2 = AttributesEnum.Customnumber2.index();
  public static final int CUSTOMNUMBER3 = AttributesEnum.Customnumber3.index();
  public static final int CUSTOMNUMBER4 = AttributesEnum.Customnumber4.index();
  public static final int CUSTOMNUMBER5 = AttributesEnum.Customnumber5.index();
  public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
  public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
  public static final int CASECOUNTRYLOV1 = AttributesEnum.CaseCountryLOV1.index();
  public static final int FNDUSERSALLLOV1 = AttributesEnum.FndUsersAllLov1.index();
  public static final int CASERESTRICTEDCITYLOV1 = AttributesEnum.CaseRestrictedCityLOV1.index();

  /**
   * This is the default constructor (do not remove).
   */
    public XwrlRequestEntityColumnsViewRowImpl() {
    }

    /**
     * Gets XwrlRequestEntityColumns entity object.
     * @return the XwrlRequestEntityColumns
     */
    public EntityImpl getXwrlRequestEntityColumns() {
        return (EntityImpl) getEntity(ENTITY_XWRLREQUESTENTITYCOLUMNS);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public BigDecimal getId() {
        return (BigDecimal) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(BigDecimal value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public BigDecimal getRequestId() {
        return (BigDecimal) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(BigDecimal value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for LISTSUBKEY using the alias name Listsubkey.
     * @return the LISTSUBKEY
     */
    public String getListsubkey() {
        return (String) getAttributeInternal(LISTSUBKEY);
    }

    /**
     * Sets <code>value</code> as attribute value for LISTSUBKEY using the alias name Listsubkey.
     * @param value value to set the LISTSUBKEY
     */
    public void setListsubkey(String value) {
        setAttributeInternal(LISTSUBKEY, value);
    }

    /**
     * Gets the attribute value for LISTRECORDTYPE using the alias name Listrecordtype.
     * @return the LISTRECORDTYPE
     */
    public String getListrecordtype() {
        return (String) getAttributeInternal(LISTRECORDTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LISTRECORDTYPE using the alias name Listrecordtype.
     * @param value value to set the LISTRECORDTYPE
     */
    public void setListrecordtype(String value) {
        setAttributeInternal(LISTRECORDTYPE, value);
    }

    /**
     * Gets the attribute value for LISTRECORDORIGIN using the alias name Listrecordorigin.
     * @return the LISTRECORDORIGIN
     */
    public String getListrecordorigin() {
        return (String) getAttributeInternal(LISTRECORDORIGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LISTRECORDORIGIN using the alias name Listrecordorigin.
     * @param value value to set the LISTRECORDORIGIN
     */
    public void setListrecordorigin(String value) {
        setAttributeInternal(LISTRECORDORIGIN, value);
    }

    /**
     * Gets the attribute value for CUSTID using the alias name Custid.
     * @return the CUSTID
     */
    public String getCustid() {
        return (String) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTID using the alias name Custid.
     * @param value value to set the CUSTID
     */
    public void setCustid(String value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for CUSTSUBID using the alias name Custsubid.
     * @return the CUSTSUBID
     */
    public String getCustsubid() {
        return (String) getAttributeInternal(CUSTSUBID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTSUBID using the alias name Custsubid.
     * @param value value to set the CUSTSUBID
     */
    public void setCustsubid(String value) {
        setAttributeInternal(CUSTSUBID, value);
    }

    /**
     * Gets the attribute value for REGISTRATIONNUMBER using the alias name Registrationnumber.
     * @return the REGISTRATIONNUMBER
     */
    public String getRegistrationnumber() {
        return (String) getAttributeInternal(REGISTRATIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REGISTRATIONNUMBER using the alias name Registrationnumber.
     * @param value value to set the REGISTRATIONNUMBER
     */
    public void setRegistrationnumber(String value) {
        setAttributeInternal(REGISTRATIONNUMBER, value);
    }

    /**
     * Gets the attribute value for ENTITYNAME using the alias name Entityname.
     * @return the ENTITYNAME
     */
    public String getEntityname() {
        return (String) getAttributeInternal(ENTITYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTITYNAME using the alias name Entityname.
     * @param value value to set the ENTITYNAME
     */
    public void setEntityname(String value) {
        setAttributeInternal(ENTITYNAME, value);
    }

    /**
     * Gets the attribute value for NAMETYPE using the alias name Nametype.
     * @return the NAMETYPE
     */
    public String getNametype() {
        return (String) getAttributeInternal(NAMETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for NAMETYPE using the alias name Nametype.
     * @param value value to set the NAMETYPE
     */
    public void setNametype(String value) {
        setAttributeInternal(NAMETYPE, value);
    }

    /**
     * Gets the attribute value for NAMEQUALITY using the alias name Namequality.
     * @return the NAMEQUALITY
     */
    public String getNamequality() {
        return (String) getAttributeInternal(NAMEQUALITY);
    }

    /**
     * Sets <code>value</code> as attribute value for NAMEQUALITY using the alias name Namequality.
     * @param value value to set the NAMEQUALITY
     */
    public void setNamequality(String value) {
        setAttributeInternal(NAMEQUALITY, value);
    }

    /**
     * Gets the attribute value for PRIMARYNAME using the alias name Primaryname.
     * @return the PRIMARYNAME
     */
    public String getPrimaryname() {
        return (String) getAttributeInternal(PRIMARYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PRIMARYNAME using the alias name Primaryname.
     * @param value value to set the PRIMARYNAME
     */
    public void setPrimaryname(String value) {
        setAttributeInternal(PRIMARYNAME, value);
    }

    /**
     * Gets the attribute value for ORIGINALSCRIPTNAME using the alias name Originalscriptname.
     * @return the ORIGINALSCRIPTNAME
     */
    public String getOriginalscriptname() {
        return (String) getAttributeInternal(ORIGINALSCRIPTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ORIGINALSCRIPTNAME using the alias name Originalscriptname.
     * @param value value to set the ORIGINALSCRIPTNAME
     */
    public void setOriginalscriptname(String value) {
        setAttributeInternal(ORIGINALSCRIPTNAME, value);
    }

    /**
     * Gets the attribute value for ALIASISACRONYM using the alias name Aliasisacronym.
     * @return the ALIASISACRONYM
     */
    public String getAliasisacronym() {
        return (String) getAttributeInternal(ALIASISACRONYM);
    }

    /**
     * Sets <code>value</code> as attribute value for ALIASISACRONYM using the alias name Aliasisacronym.
     * @param value value to set the ALIASISACRONYM
     */
    public void setAliasisacronym(String value) {
        setAttributeInternal(ALIASISACRONYM, value);
    }

    /**
     * Gets the attribute value for ADDRESS1 using the alias name Address1.
     * @return the ADDRESS1
     */
    public String getAddress1() {
        return (String) getAttributeInternal(ADDRESS1);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS1 using the alias name Address1.
     * @param value value to set the ADDRESS1
     */
    public void setAddress1(String value) {
        setAttributeInternal(ADDRESS1, value);
    }

    /**
     * Gets the attribute value for ADDRESS2 using the alias name Address2.
     * @return the ADDRESS2
     */
    public String getAddress2() {
        return (String) getAttributeInternal(ADDRESS2);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS2 using the alias name Address2.
     * @param value value to set the ADDRESS2
     */
    public void setAddress2(String value) {
        setAttributeInternal(ADDRESS2, value);
    }

    /**
     * Gets the attribute value for ADDRESS3 using the alias name Address3.
     * @return the ADDRESS3
     */
    public String getAddress3() {
        return (String) getAttributeInternal(ADDRESS3);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS3 using the alias name Address3.
     * @param value value to set the ADDRESS3
     */
    public void setAddress3(String value) {
        setAttributeInternal(ADDRESS3, value);
    }

    /**
     * Gets the attribute value for ADDRESS4 using the alias name Address4.
     * @return the ADDRESS4
     */
    public String getAddress4() {
        return (String) getAttributeInternal(ADDRESS4);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS4 using the alias name Address4.
     * @param value value to set the ADDRESS4
     */
    public void setAddress4(String value) {
        setAttributeInternal(ADDRESS4, value);
    }

    /**
     * Gets the attribute value for CITY using the alias name City.
     * @return the CITY
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY using the alias name City.
     * @param value value to set the CITY
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(String value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for POSTALCODE using the alias name Postalcode.
     * @return the POSTALCODE
     */
    public String getPostalcode() {
        return (String) getAttributeInternal(POSTALCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTALCODE using the alias name Postalcode.
     * @param value value to set the POSTALCODE
     */
    public void setPostalcode(String value) {
        setAttributeInternal(POSTALCODE, value);
    }

    /**
     * Gets the attribute value for ADDRESSCOUNTRYCODE using the alias name Addresscountrycode.
     * @return the ADDRESSCOUNTRYCODE
     */
    public String getAddresscountrycode() {
        return (String) getAttributeInternal(ADDRESSCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESSCOUNTRYCODE using the alias name Addresscountrycode.
     * @param value value to set the ADDRESSCOUNTRYCODE
     */
    public void setAddresscountrycode(String value) {
        setAttributeInternal(ADDRESSCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for REGISTRATIONCOUNTRYCODE using the alias name Registrationcountrycode.
     * @return the REGISTRATIONCOUNTRYCODE
     */
    public String getRegistrationcountrycode() {
        return (String) getAttributeInternal(REGISTRATIONCOUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for REGISTRATIONCOUNTRYCODE using the alias name Registrationcountrycode.
     * @param value value to set the REGISTRATIONCOUNTRYCODE
     */
    public void setRegistrationcountrycode(String value) {
        setAttributeInternal(REGISTRATIONCOUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for OPERATINGCOUNTRYCODES using the alias name Operatingcountrycodes.
     * @return the OPERATINGCOUNTRYCODES
     */
    public String getOperatingcountrycodes() {
        return (String) getAttributeInternal(OPERATINGCOUNTRYCODES);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATINGCOUNTRYCODES using the alias name Operatingcountrycodes.
     * @param value value to set the OPERATINGCOUNTRYCODES
     */
    public void setOperatingcountrycodes(String value) {
        setAttributeInternal(OPERATINGCOUNTRYCODES, value);
    }

    /**
     * Gets the attribute value for PROFILEHYPERLINK using the alias name Profilehyperlink.
     * @return the PROFILEHYPERLINK
     */
    public String getProfilehyperlink() {
        return (String) getAttributeInternal(PROFILEHYPERLINK);
    }

    /**
     * Sets <code>value</code> as attribute value for PROFILEHYPERLINK using the alias name Profilehyperlink.
     * @param value value to set the PROFILEHYPERLINK
     */
    public void setProfilehyperlink(String value) {
        setAttributeInternal(PROFILEHYPERLINK, value);
    }

    /**
     * Gets the attribute value for RISKSCORE using the alias name Riskscore.
     * @return the RISKSCORE
     */
    public String getRiskscore() {
        return (String) getAttributeInternal(RISKSCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for RISKSCORE using the alias name Riskscore.
     * @param value value to set the RISKSCORE
     */
    public void setRiskscore(String value) {
        setAttributeInternal(RISKSCORE, value);
    }

    /**
     * Gets the attribute value for DATACONFIDENCESCORE using the alias name Dataconfidencescore.
     * @return the DATACONFIDENCESCORE
     */
    public String getDataconfidencescore() {
        return (String) getAttributeInternal(DATACONFIDENCESCORE);
    }

    /**
     * Sets <code>value</code> as attribute value for DATACONFIDENCESCORE using the alias name Dataconfidencescore.
     * @param value value to set the DATACONFIDENCESCORE
     */
    public void setDataconfidencescore(String value) {
        setAttributeInternal(DATACONFIDENCESCORE, value);
    }

    /**
     * Gets the attribute value for DATACONFIDENCECOMMENT using the alias name Dataconfidencecomment.
     * @return the DATACONFIDENCECOMMENT
     */
    public String getDataconfidencecomment() {
        return (String) getAttributeInternal(DATACONFIDENCECOMMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DATACONFIDENCECOMMENT using the alias name Dataconfidencecomment.
     * @param value value to set the DATACONFIDENCECOMMENT
     */
    public void setDataconfidencecomment(String value) {
        setAttributeInternal(DATACONFIDENCECOMMENT, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING1 using the alias name Customstring1.
     * @return the CUSTOMSTRING1
     */
    public String getCustomstring1() {
        return (String) getAttributeInternal(CUSTOMSTRING1);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING1 using the alias name Customstring1.
     * @param value value to set the CUSTOMSTRING1
     */
    public void setCustomstring1(String value) {
        setAttributeInternal(CUSTOMSTRING1, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING2 using the alias name Customstring2.
     * @return the CUSTOMSTRING2
     */
    public String getCustomstring2() {
        return (String) getAttributeInternal(CUSTOMSTRING2);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING2 using the alias name Customstring2.
     * @param value value to set the CUSTOMSTRING2
     */
    public void setCustomstring2(String value) {
        setAttributeInternal(CUSTOMSTRING2, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING3 using the alias name Customstring3.
     * @return the CUSTOMSTRING3
     */
    public String getCustomstring3() {
        return (String) getAttributeInternal(CUSTOMSTRING3);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING3 using the alias name Customstring3.
     * @param value value to set the CUSTOMSTRING3
     */
    public void setCustomstring3(String value) {
        setAttributeInternal(CUSTOMSTRING3, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING4 using the alias name Customstring4.
     * @return the CUSTOMSTRING4
     */
    public String getCustomstring4() {
        return (String) getAttributeInternal(CUSTOMSTRING4);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING4 using the alias name Customstring4.
     * @param value value to set the CUSTOMSTRING4
     */
    public void setCustomstring4(String value) {
        setAttributeInternal(CUSTOMSTRING4, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING5 using the alias name Customstring5.
     * @return the CUSTOMSTRING5
     */
    public String getCustomstring5() {
        return (String) getAttributeInternal(CUSTOMSTRING5);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING5 using the alias name Customstring5.
     * @param value value to set the CUSTOMSTRING5
     */
    public void setCustomstring5(String value) {
        setAttributeInternal(CUSTOMSTRING5, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING6 using the alias name Customstring6.
     * @return the CUSTOMSTRING6
     */
    public String getCustomstring6() {
        return (String) getAttributeInternal(CUSTOMSTRING6);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING6 using the alias name Customstring6.
     * @param value value to set the CUSTOMSTRING6
     */
    public void setCustomstring6(String value) {
        setAttributeInternal(CUSTOMSTRING6, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING7 using the alias name Customstring7.
     * @return the CUSTOMSTRING7
     */
    public String getCustomstring7() {
        return (String) getAttributeInternal(CUSTOMSTRING7);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING7 using the alias name Customstring7.
     * @param value value to set the CUSTOMSTRING7
     */
    public void setCustomstring7(String value) {
        setAttributeInternal(CUSTOMSTRING7, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING8 using the alias name Customstring8.
     * @return the CUSTOMSTRING8
     */
    public String getCustomstring8() {
        return (String) getAttributeInternal(CUSTOMSTRING8);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING8 using the alias name Customstring8.
     * @param value value to set the CUSTOMSTRING8
     */
    public void setCustomstring8(String value) {
        setAttributeInternal(CUSTOMSTRING8, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING9 using the alias name Customstring9.
     * @return the CUSTOMSTRING9
     */
    public String getCustomstring9() {
        return (String) getAttributeInternal(CUSTOMSTRING9);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING9 using the alias name Customstring9.
     * @param value value to set the CUSTOMSTRING9
     */
    public void setCustomstring9(String value) {
        setAttributeInternal(CUSTOMSTRING9, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING10 using the alias name Customstring10.
     * @return the CUSTOMSTRING10
     */
    public String getCustomstring10() {
        return (String) getAttributeInternal(CUSTOMSTRING10);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING10 using the alias name Customstring10.
     * @param value value to set the CUSTOMSTRING10
     */
    public void setCustomstring10(String value) {
        setAttributeInternal(CUSTOMSTRING10, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING11 using the alias name Customstring11.
     * @return the CUSTOMSTRING11
     */
    public String getCustomstring11() {
        return (String) getAttributeInternal(CUSTOMSTRING11);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING11 using the alias name Customstring11.
     * @param value value to set the CUSTOMSTRING11
     */
    public void setCustomstring11(String value) {
        setAttributeInternal(CUSTOMSTRING11, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING12 using the alias name Customstring12.
     * @return the CUSTOMSTRING12
     */
    public String getCustomstring12() {
        return (String) getAttributeInternal(CUSTOMSTRING12);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING12 using the alias name Customstring12.
     * @param value value to set the CUSTOMSTRING12
     */
    public void setCustomstring12(String value) {
        setAttributeInternal(CUSTOMSTRING12, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING13 using the alias name Customstring13.
     * @return the CUSTOMSTRING13
     */
    public String getCustomstring13() {
        return (String) getAttributeInternal(CUSTOMSTRING13);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING13 using the alias name Customstring13.
     * @param value value to set the CUSTOMSTRING13
     */
    public void setCustomstring13(String value) {
        setAttributeInternal(CUSTOMSTRING13, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING14 using the alias name Customstring14.
     * @return the CUSTOMSTRING14
     */
    public String getCustomstring14() {
        return (String) getAttributeInternal(CUSTOMSTRING14);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING14 using the alias name Customstring14.
     * @param value value to set the CUSTOMSTRING14
     */
    public void setCustomstring14(String value) {
        setAttributeInternal(CUSTOMSTRING14, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING15 using the alias name Customstring15.
     * @return the CUSTOMSTRING15
     */
    public String getCustomstring15() {
        return (String) getAttributeInternal(CUSTOMSTRING15);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING15 using the alias name Customstring15.
     * @param value value to set the CUSTOMSTRING15
     */
    public void setCustomstring15(String value) {
        setAttributeInternal(CUSTOMSTRING15, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING16 using the alias name Customstring16.
     * @return the CUSTOMSTRING16
     */
    public String getCustomstring16() {
        return (String) getAttributeInternal(CUSTOMSTRING16);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING16 using the alias name Customstring16.
     * @param value value to set the CUSTOMSTRING16
     */
    public void setCustomstring16(String value) {
        setAttributeInternal(CUSTOMSTRING16, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING17 using the alias name Customstring17.
     * @return the CUSTOMSTRING17
     */
    public String getCustomstring17() {
        return (String) getAttributeInternal(CUSTOMSTRING17);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING17 using the alias name Customstring17.
     * @param value value to set the CUSTOMSTRING17
     */
    public void setCustomstring17(String value) {
        setAttributeInternal(CUSTOMSTRING17, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING18 using the alias name Customstring18.
     * @return the CUSTOMSTRING18
     */
    public String getCustomstring18() {
        return (String) getAttributeInternal(CUSTOMSTRING18);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING18 using the alias name Customstring18.
     * @param value value to set the CUSTOMSTRING18
     */
    public void setCustomstring18(String value) {
        setAttributeInternal(CUSTOMSTRING18, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING19 using the alias name Customstring19.
     * @return the CUSTOMSTRING19
     */
    public String getCustomstring19() {
        return (String) getAttributeInternal(CUSTOMSTRING19);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING19 using the alias name Customstring19.
     * @param value value to set the CUSTOMSTRING19
     */
    public void setCustomstring19(String value) {
        setAttributeInternal(CUSTOMSTRING19, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING20 using the alias name Customstring20.
     * @return the CUSTOMSTRING20
     */
    public String getCustomstring20() {
        return (String) getAttributeInternal(CUSTOMSTRING20);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING20 using the alias name Customstring20.
     * @param value value to set the CUSTOMSTRING20
     */
    public void setCustomstring20(String value) {
        setAttributeInternal(CUSTOMSTRING20, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING21 using the alias name Customstring21.
     * @return the CUSTOMSTRING21
     */
    public String getCustomstring21() {
        return (String) getAttributeInternal(CUSTOMSTRING21);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING21 using the alias name Customstring21.
     * @param value value to set the CUSTOMSTRING21
     */
    public void setCustomstring21(String value) {
        setAttributeInternal(CUSTOMSTRING21, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING22 using the alias name Customstring22.
     * @return the CUSTOMSTRING22
     */
    public String getCustomstring22() {
        return (String) getAttributeInternal(CUSTOMSTRING22);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING22 using the alias name Customstring22.
     * @param value value to set the CUSTOMSTRING22
     */
    public void setCustomstring22(String value) {
        setAttributeInternal(CUSTOMSTRING22, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING23 using the alias name Customstring23.
     * @return the CUSTOMSTRING23
     */
    public String getCustomstring23() {
        return (String) getAttributeInternal(CUSTOMSTRING23);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING23 using the alias name Customstring23.
     * @param value value to set the CUSTOMSTRING23
     */
    public void setCustomstring23(String value) {
        setAttributeInternal(CUSTOMSTRING23, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING24 using the alias name Customstring24.
     * @return the CUSTOMSTRING24
     */
    public String getCustomstring24() {
        return (String) getAttributeInternal(CUSTOMSTRING24);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING24 using the alias name Customstring24.
     * @param value value to set the CUSTOMSTRING24
     */
    public void setCustomstring24(String value) {
        setAttributeInternal(CUSTOMSTRING24, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING25 using the alias name Customstring25.
     * @return the CUSTOMSTRING25
     */
    public String getCustomstring25() {
        return (String) getAttributeInternal(CUSTOMSTRING25);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING25 using the alias name Customstring25.
     * @param value value to set the CUSTOMSTRING25
     */
    public void setCustomstring25(String value) {
        setAttributeInternal(CUSTOMSTRING25, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING26 using the alias name Customstring26.
     * @return the CUSTOMSTRING26
     */
    public String getCustomstring26() {
        return (String) getAttributeInternal(CUSTOMSTRING26);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING26 using the alias name Customstring26.
     * @param value value to set the CUSTOMSTRING26
     */
    public void setCustomstring26(String value) {
        setAttributeInternal(CUSTOMSTRING26, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING27 using the alias name Customstring27.
     * @return the CUSTOMSTRING27
     */
    public String getCustomstring27() {
        return (String) getAttributeInternal(CUSTOMSTRING27);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING27 using the alias name Customstring27.
     * @param value value to set the CUSTOMSTRING27
     */
    public void setCustomstring27(String value) {
        setAttributeInternal(CUSTOMSTRING27, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING28 using the alias name Customstring28.
     * @return the CUSTOMSTRING28
     */
    public String getCustomstring28() {
        return (String) getAttributeInternal(CUSTOMSTRING28);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING28 using the alias name Customstring28.
     * @param value value to set the CUSTOMSTRING28
     */
    public void setCustomstring28(String value) {
        setAttributeInternal(CUSTOMSTRING28, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING29 using the alias name Customstring29.
     * @return the CUSTOMSTRING29
     */
    public String getCustomstring29() {
        return (String) getAttributeInternal(CUSTOMSTRING29);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING29 using the alias name Customstring29.
     * @param value value to set the CUSTOMSTRING29
     */
    public void setCustomstring29(String value) {
        setAttributeInternal(CUSTOMSTRING29, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING30 using the alias name Customstring30.
     * @return the CUSTOMSTRING30
     */
    public String getCustomstring30() {
        return (String) getAttributeInternal(CUSTOMSTRING30);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING30 using the alias name Customstring30.
     * @param value value to set the CUSTOMSTRING30
     */
    public void setCustomstring30(String value) {
        setAttributeInternal(CUSTOMSTRING30, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING31 using the alias name Customstring31.
     * @return the CUSTOMSTRING31
     */
    public String getCustomstring31() {
        return (String) getAttributeInternal(CUSTOMSTRING31);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING31 using the alias name Customstring31.
     * @param value value to set the CUSTOMSTRING31
     */
    public void setCustomstring31(String value) {
        setAttributeInternal(CUSTOMSTRING31, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING32 using the alias name Customstring32.
     * @return the CUSTOMSTRING32
     */
    public String getCustomstring32() {
        return (String) getAttributeInternal(CUSTOMSTRING32);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING32 using the alias name Customstring32.
     * @param value value to set the CUSTOMSTRING32
     */
    public void setCustomstring32(String value) {
        setAttributeInternal(CUSTOMSTRING32, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING33 using the alias name Customstring33.
     * @return the CUSTOMSTRING33
     */
    public String getCustomstring33() {
        return (String) getAttributeInternal(CUSTOMSTRING33);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING33 using the alias name Customstring33.
     * @param value value to set the CUSTOMSTRING33
     */
    public void setCustomstring33(String value) {
        setAttributeInternal(CUSTOMSTRING33, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING34 using the alias name Customstring34.
     * @return the CUSTOMSTRING34
     */
    public String getCustomstring34() {
        return (String) getAttributeInternal(CUSTOMSTRING34);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING34 using the alias name Customstring34.
     * @param value value to set the CUSTOMSTRING34
     */
    public void setCustomstring34(String value) {
        setAttributeInternal(CUSTOMSTRING34, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING35 using the alias name Customstring35.
     * @return the CUSTOMSTRING35
     */
    public String getCustomstring35() {
        return (String) getAttributeInternal(CUSTOMSTRING35);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING35 using the alias name Customstring35.
     * @param value value to set the CUSTOMSTRING35
     */
    public void setCustomstring35(String value) {
        setAttributeInternal(CUSTOMSTRING35, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING36 using the alias name Customstring36.
     * @return the CUSTOMSTRING36
     */
    public String getCustomstring36() {
        return (String) getAttributeInternal(CUSTOMSTRING36);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING36 using the alias name Customstring36.
     * @param value value to set the CUSTOMSTRING36
     */
    public void setCustomstring36(String value) {
        setAttributeInternal(CUSTOMSTRING36, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING37 using the alias name Customstring37.
     * @return the CUSTOMSTRING37
     */
    public String getCustomstring37() {
        return (String) getAttributeInternal(CUSTOMSTRING37);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING37 using the alias name Customstring37.
     * @param value value to set the CUSTOMSTRING37
     */
    public void setCustomstring37(String value) {
        setAttributeInternal(CUSTOMSTRING37, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING38 using the alias name Customstring38.
     * @return the CUSTOMSTRING38
     */
    public String getCustomstring38() {
        return (String) getAttributeInternal(CUSTOMSTRING38);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING38 using the alias name Customstring38.
     * @param value value to set the CUSTOMSTRING38
     */
    public void setCustomstring38(String value) {
        setAttributeInternal(CUSTOMSTRING38, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING39 using the alias name Customstring39.
     * @return the CUSTOMSTRING39
     */
    public String getCustomstring39() {
        return (String) getAttributeInternal(CUSTOMSTRING39);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING39 using the alias name Customstring39.
     * @param value value to set the CUSTOMSTRING39
     */
    public void setCustomstring39(String value) {
        setAttributeInternal(CUSTOMSTRING39, value);
    }

    /**
     * Gets the attribute value for CUSTOMSTRING40 using the alias name Customstring40.
     * @return the CUSTOMSTRING40
     */
    public String getCustomstring40() {
        return (String) getAttributeInternal(CUSTOMSTRING40);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMSTRING40 using the alias name Customstring40.
     * @param value value to set the CUSTOMSTRING40
     */
    public void setCustomstring40(String value) {
        setAttributeInternal(CUSTOMSTRING40, value);
    }

    /**
     * Gets the attribute value for CUSTOMDATE1 using the alias name Customdate1.
     * @return the CUSTOMDATE1
     */
    public String getCustomdate1() {
        return (String) getAttributeInternal(CUSTOMDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMDATE1 using the alias name Customdate1.
     * @param value value to set the CUSTOMDATE1
     */
    public void setCustomdate1(String value) {
        setAttributeInternal(CUSTOMDATE1, value);
    }

    /**
     * Gets the attribute value for CUSTOMDATE2 using the alias name Customdate2.
     * @return the CUSTOMDATE2
     */
    public String getCustomdate2() {
        return (String) getAttributeInternal(CUSTOMDATE2);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMDATE2 using the alias name Customdate2.
     * @param value value to set the CUSTOMDATE2
     */
    public void setCustomdate2(String value) {
        setAttributeInternal(CUSTOMDATE2, value);
    }

    /**
     * Gets the attribute value for CUSTOMDATE3 using the alias name Customdate3.
     * @return the CUSTOMDATE3
     */
    public String getCustomdate3() {
        return (String) getAttributeInternal(CUSTOMDATE3);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMDATE3 using the alias name Customdate3.
     * @param value value to set the CUSTOMDATE3
     */
    public void setCustomdate3(String value) {
        setAttributeInternal(CUSTOMDATE3, value);
    }

    /**
     * Gets the attribute value for CUSTOMDATE4 using the alias name Customdate4.
     * @return the CUSTOMDATE4
     */
    public String getCustomdate4() {
        return (String) getAttributeInternal(CUSTOMDATE4);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMDATE4 using the alias name Customdate4.
     * @param value value to set the CUSTOMDATE4
     */
    public void setCustomdate4(String value) {
        setAttributeInternal(CUSTOMDATE4, value);
    }

    /**
     * Gets the attribute value for CUSTOMDATE5 using the alias name Customdate5.
     * @return the CUSTOMDATE5
     */
    public String getCustomdate5() {
        return (String) getAttributeInternal(CUSTOMDATE5);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMDATE5 using the alias name Customdate5.
     * @param value value to set the CUSTOMDATE5
     */
    public void setCustomdate5(String value) {
        setAttributeInternal(CUSTOMDATE5, value);
    }

    /**
     * Gets the attribute value for CUSTOMNUMBER1 using the alias name Customnumber1.
     * @return the CUSTOMNUMBER1
     */
    public String getCustomnumber1() {
        return (String) getAttributeInternal(CUSTOMNUMBER1);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMNUMBER1 using the alias name Customnumber1.
     * @param value value to set the CUSTOMNUMBER1
     */
    public void setCustomnumber1(String value) {
        setAttributeInternal(CUSTOMNUMBER1, value);
    }

    /**
     * Gets the attribute value for CUSTOMNUMBER2 using the alias name Customnumber2.
     * @return the CUSTOMNUMBER2
     */
    public String getCustomnumber2() {
        return (String) getAttributeInternal(CUSTOMNUMBER2);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMNUMBER2 using the alias name Customnumber2.
     * @param value value to set the CUSTOMNUMBER2
     */
    public void setCustomnumber2(String value) {
        setAttributeInternal(CUSTOMNUMBER2, value);
    }

    /**
     * Gets the attribute value for CUSTOMNUMBER3 using the alias name Customnumber3.
     * @return the CUSTOMNUMBER3
     */
    public String getCustomnumber3() {
        return (String) getAttributeInternal(CUSTOMNUMBER3);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMNUMBER3 using the alias name Customnumber3.
     * @param value value to set the CUSTOMNUMBER3
     */
    public void setCustomnumber3(String value) {
        setAttributeInternal(CUSTOMNUMBER3, value);
    }

    /**
     * Gets the attribute value for CUSTOMNUMBER4 using the alias name Customnumber4.
     * @return the CUSTOMNUMBER4
     */
    public String getCustomnumber4() {
        return (String) getAttributeInternal(CUSTOMNUMBER4);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMNUMBER4 using the alias name Customnumber4.
     * @param value value to set the CUSTOMNUMBER4
     */
    public void setCustomnumber4(String value) {
        setAttributeInternal(CUSTOMNUMBER4, value);
    }

    /**
     * Gets the attribute value for CUSTOMNUMBER5 using the alias name Customnumber5.
     * @return the CUSTOMNUMBER5
     */
    public String getCustomnumber5() {
        return (String) getAttributeInternal(CUSTOMNUMBER5);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMNUMBER5 using the alias name Customnumber5.
     * @param value value to set the CUSTOMNUMBER5
     */
    public void setCustomnumber5(String value) {
        setAttributeInternal(CUSTOMNUMBER5, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Long getLastUpdatedBy() {
        return (Long) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Long value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Long getCreatedBy() {
        return (Long) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Long value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Long getLastUpdateLogin() {
        return (Long) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Long value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CaseCountryLOV1.
     */
    public RowSet getCaseCountryLOV1() {
        return (RowSet) getAttributeInternal(CASECOUNTRYLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FndUsersAllLov1.
     */
    public RowSet getFndUsersAllLov1() {
        return (RowSet) getAttributeInternal(FNDUSERSALLLOV1);
    }

  /**
   * Gets the view accessor <code>RowSet</code> CaseRestrictedCityLOV1.
   */
  public RowSet getCaseRestrictedCityLOV1()
  {
    return (RowSet) getAttributeInternal(CASERESTRICTEDCITYLOV1);
  }
}

