/* Create Production DB Link */   
   
drop DATABASE LINK "EBSTOOWS2.CORESYS.COM";

CREATE DATABASE LINK "EBSTOOWS2.CORESYS.COM" CONNECT TO "SYSTEM" IDENTIFIED BY Ora11495 USING 'iripsp03.coresys.com:1521/IRIPOWS';
   
/* Create Non-Production DB Link */   
   
drop DATABASE LINK "EBSTOOWS2.CORESYS.COM";

CREATE DATABASE LINK "EBSTOOWS2.CORESYS.COM" CONNECT TO "SYSTEM" IDENTIFIED BY Ora11495 USING 'iripsd03.coresys.com:1521/IRIDROWS';