CREATE OR REPLACE TRIGGER XWRL_REQ_ENT_COLS_AFT_IUD_TRG
AFTER INSERT OR UPDATE OR DELETE ON XWRL_REQUEST_ENTITY_COLUMNS
FOR EACH ROW
DECLARE

cursor c1 is
select table_name, column_name
from all_tab_columns
where table_name = 'XWRL_REQUEST_ENTITY_COLUMNS'
and data_type not in  ('XMLTYPE')
and column_name not in  ('SOAP_QUERY');

v_rec XWRL_AUDIT_LOG%rowtype;
p_row_action varchar2(20);
v_user_id  NUMBER  := apps.fnd_profile.value('USER_ID');
v_login_id NUMBER  := apps.fnd_profile.value('LOGIN_ID');
v_rec XWRL_AUDIT_LOG%rowtype;
v_rec.creation_date     := SYSDATE;
v_rec.last_update_date  := SYSDATE;
v_rec.last_updated_by   := v_user_id;
v_rec.created_by        := v_user_id;
v_rec.last_update_login := v_login_id;

BEGIN
IF INSERTING THEN 
p_row_action := 'INSERT';
ELSIF UPDATING THEN 
p_row_action := 'UPDATE';
ELSIF DELETING THEN 
p_row_action := 'DELETE';
END IF;

BEGIN
IF NVL(TO_CHAR(:OLD.CREATED_BY),'X') <> NVL(TO_CHAR(:NEW.CREATED_BY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CREATED_BY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CREATED_BY;
v_rec.NEW_VALUE := :NEW.CREATED_BY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATE_LOGIN),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATE_LOGIN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LAST_UPDATE_LOGIN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATE_LOGIN;
v_rec.NEW_VALUE := :NEW.LAST_UPDATE_LOGIN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ID),'X') <> NVL(TO_CHAR(:NEW.ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ID;
v_rec.NEW_VALUE := :NEW.ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.REQUEST_ID),'X') <> NVL(TO_CHAR(:NEW.REQUEST_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'REQUEST_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.REQUEST_ID;
v_rec.NEW_VALUE := :NEW.REQUEST_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LISTSUBKEY),'X') <> NVL(TO_CHAR(:NEW.LISTSUBKEY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LISTSUBKEY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LISTSUBKEY;
v_rec.NEW_VALUE := :NEW.LISTSUBKEY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LISTRECORDTYPE),'X') <> NVL(TO_CHAR(:NEW.LISTRECORDTYPE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LISTRECORDTYPE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LISTRECORDTYPE;
v_rec.NEW_VALUE := :NEW.LISTRECORDTYPE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LISTRECORDORIGIN),'X') <> NVL(TO_CHAR(:NEW.LISTRECORDORIGIN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LISTRECORDORIGIN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LISTRECORDORIGIN;
v_rec.NEW_VALUE := :NEW.LISTRECORDORIGIN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTID),'X') <> NVL(TO_CHAR(:NEW.CUSTID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTID;
v_rec.NEW_VALUE := :NEW.CUSTID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTSUBID),'X') <> NVL(TO_CHAR(:NEW.CUSTSUBID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTSUBID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTSUBID;
v_rec.NEW_VALUE := :NEW.CUSTSUBID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.REGISTRATIONNUMBER),'X') <> NVL(TO_CHAR(:NEW.REGISTRATIONNUMBER),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'REGISTRATIONNUMBER';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.REGISTRATIONNUMBER;
v_rec.NEW_VALUE := :NEW.REGISTRATIONNUMBER;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ENTITYNAME),'X') <> NVL(TO_CHAR(:NEW.ENTITYNAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ENTITYNAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ENTITYNAME;
v_rec.NEW_VALUE := :NEW.ENTITYNAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.NAMETYPE),'X') <> NVL(TO_CHAR(:NEW.NAMETYPE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'NAMETYPE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.NAMETYPE;
v_rec.NEW_VALUE := :NEW.NAMETYPE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.NAMEQUALITY),'X') <> NVL(TO_CHAR(:NEW.NAMEQUALITY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'NAMEQUALITY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.NAMEQUALITY;
v_rec.NEW_VALUE := :NEW.NAMEQUALITY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.PRIMARYNAME),'X') <> NVL(TO_CHAR(:NEW.PRIMARYNAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'PRIMARYNAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.PRIMARYNAME;
v_rec.NEW_VALUE := :NEW.PRIMARYNAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ORIGINALSCRIPTNAME),'X') <> NVL(TO_CHAR(:NEW.ORIGINALSCRIPTNAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ORIGINALSCRIPTNAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ORIGINALSCRIPTNAME;
v_rec.NEW_VALUE := :NEW.ORIGINALSCRIPTNAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ALIASISACRONYM),'X') <> NVL(TO_CHAR(:NEW.ALIASISACRONYM),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ALIASISACRONYM';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ALIASISACRONYM;
v_rec.NEW_VALUE := :NEW.ALIASISACRONYM;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ADDRESS1),'X') <> NVL(TO_CHAR(:NEW.ADDRESS1),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ADDRESS1';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ADDRESS1;
v_rec.NEW_VALUE := :NEW.ADDRESS1;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ADDRESS2),'X') <> NVL(TO_CHAR(:NEW.ADDRESS2),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ADDRESS2';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ADDRESS2;
v_rec.NEW_VALUE := :NEW.ADDRESS2;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ADDRESS3),'X') <> NVL(TO_CHAR(:NEW.ADDRESS3),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ADDRESS3';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ADDRESS3;
v_rec.NEW_VALUE := :NEW.ADDRESS3;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ADDRESS4),'X') <> NVL(TO_CHAR(:NEW.ADDRESS4),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ADDRESS4';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ADDRESS4;
v_rec.NEW_VALUE := :NEW.ADDRESS4;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CITY),'X') <> NVL(TO_CHAR(:NEW.CITY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CITY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CITY;
v_rec.NEW_VALUE := :NEW.CITY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.STATE),'X') <> NVL(TO_CHAR(:NEW.STATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'STATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.STATE;
v_rec.NEW_VALUE := :NEW.STATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.POSTALCODE),'X') <> NVL(TO_CHAR(:NEW.POSTALCODE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'POSTALCODE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.POSTALCODE;
v_rec.NEW_VALUE := :NEW.POSTALCODE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ADDRESSCOUNTRYCODE),'X') <> NVL(TO_CHAR(:NEW.ADDRESSCOUNTRYCODE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'ADDRESSCOUNTRYCODE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ADDRESSCOUNTRYCODE;
v_rec.NEW_VALUE := :NEW.ADDRESSCOUNTRYCODE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.REGISTRATIONCOUNTRYCODE),'X') <> NVL(TO_CHAR(:NEW.REGISTRATIONCOUNTRYCODE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'REGISTRATIONCOUNTRYCODE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.REGISTRATIONCOUNTRYCODE;
v_rec.NEW_VALUE := :NEW.REGISTRATIONCOUNTRYCODE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.OPERATINGCOUNTRYCODES),'X') <> NVL(TO_CHAR(:NEW.OPERATINGCOUNTRYCODES),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'OPERATINGCOUNTRYCODES';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.OPERATINGCOUNTRYCODES;
v_rec.NEW_VALUE := :NEW.OPERATINGCOUNTRYCODES;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.PROFILEHYPERLINK),'X') <> NVL(TO_CHAR(:NEW.PROFILEHYPERLINK),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'PROFILEHYPERLINK';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.PROFILEHYPERLINK;
v_rec.NEW_VALUE := :NEW.PROFILEHYPERLINK;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.RISKSCORE),'X') <> NVL(TO_CHAR(:NEW.RISKSCORE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'RISKSCORE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.RISKSCORE;
v_rec.NEW_VALUE := :NEW.RISKSCORE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.DATACONFIDENCESCORE),'X') <> NVL(TO_CHAR(:NEW.DATACONFIDENCESCORE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'DATACONFIDENCESCORE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.DATACONFIDENCESCORE;
v_rec.NEW_VALUE := :NEW.DATACONFIDENCESCORE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.DATACONFIDENCECOMMENT),'X') <> NVL(TO_CHAR(:NEW.DATACONFIDENCECOMMENT),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'DATACONFIDENCECOMMENT';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.DATACONFIDENCECOMMENT;
v_rec.NEW_VALUE := :NEW.DATACONFIDENCECOMMENT;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING1),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING1),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING1';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING1;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING1;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING2),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING2),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING2';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING2;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING2;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING3),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING3),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING3';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING3;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING3;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING4),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING4),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING4';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING4;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING4;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING5),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING5),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING5';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING5;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING5;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING6),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING6),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING6';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING6;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING6;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING7),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING7),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING7';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING7;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING7;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING8),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING8),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING8';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING8;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING8;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING9),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING9),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING9';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING9;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING9;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING10),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING10),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING10';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING10;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING10;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING11),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING11),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING11';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING11;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING11;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING12),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING12),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING12';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING12;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING12;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING13),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING13),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING13';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING13;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING13;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING14),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING14),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING14';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING14;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING14;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING15),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING15),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING15';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING15;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING15;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING16),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING16),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING16';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING16;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING16;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING17),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING17),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING17';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING17;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING17;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING18),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING18),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING18';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING18;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING18;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING19),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING19),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING19';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING19;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING19;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING20),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING20),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING20';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING20;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING20;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING21),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING21),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING21';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING21;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING21;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING22),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING22),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING22';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING22;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING22;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING23),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING23),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING23';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING23;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING23;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING24),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING24),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING24';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING24;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING24;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING25),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING25),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING25';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING25;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING25;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING26),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING26),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING26';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING26;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING26;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING27),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING27),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING27';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING27;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING27;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING28),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING28),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING28';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING28;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING28;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING29),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING29),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING29';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING29;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING29;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING30),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING30),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING30';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING30;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING30;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING31),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING31),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING31';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING31;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING31;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING32),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING32),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING32';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING32;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING32;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING33),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING33),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING33';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING33;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING33;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING34),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING34),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING34';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING34;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING34;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING35),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING35),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING35';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING35;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING35;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING36),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING36),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING36';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING36;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING36;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING37),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING37),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING37';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING37;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING37;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING38),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING38),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING38';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING38;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING38;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING39),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING39),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING39';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING39;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING39;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMSTRING40),'X') <> NVL(TO_CHAR(:NEW.CUSTOMSTRING40),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMSTRING40';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMSTRING40;
v_rec.NEW_VALUE := :NEW.CUSTOMSTRING40;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMDATE1),'X') <> NVL(TO_CHAR(:NEW.CUSTOMDATE1),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMDATE1';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMDATE1;
v_rec.NEW_VALUE := :NEW.CUSTOMDATE1;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMDATE2),'X') <> NVL(TO_CHAR(:NEW.CUSTOMDATE2),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMDATE2';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMDATE2;
v_rec.NEW_VALUE := :NEW.CUSTOMDATE2;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMDATE3),'X') <> NVL(TO_CHAR(:NEW.CUSTOMDATE3),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMDATE3';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMDATE3;
v_rec.NEW_VALUE := :NEW.CUSTOMDATE3;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMDATE4),'X') <> NVL(TO_CHAR(:NEW.CUSTOMDATE4),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMDATE4';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMDATE4;
v_rec.NEW_VALUE := :NEW.CUSTOMDATE4;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMDATE5),'X') <> NVL(TO_CHAR(:NEW.CUSTOMDATE5),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMDATE5';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMDATE5;
v_rec.NEW_VALUE := :NEW.CUSTOMDATE5;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMNUMBER1),'X') <> NVL(TO_CHAR(:NEW.CUSTOMNUMBER1),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMNUMBER1';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMNUMBER1;
v_rec.NEW_VALUE := :NEW.CUSTOMNUMBER1;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMNUMBER2),'X') <> NVL(TO_CHAR(:NEW.CUSTOMNUMBER2),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMNUMBER2';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMNUMBER2;
v_rec.NEW_VALUE := :NEW.CUSTOMNUMBER2;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMNUMBER3),'X') <> NVL(TO_CHAR(:NEW.CUSTOMNUMBER3),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMNUMBER3';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMNUMBER3;
v_rec.NEW_VALUE := :NEW.CUSTOMNUMBER3;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMNUMBER4),'X') <> NVL(TO_CHAR(:NEW.CUSTOMNUMBER4),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMNUMBER4';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMNUMBER4;
v_rec.NEW_VALUE := :NEW.CUSTOMNUMBER4;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CUSTOMNUMBER5),'X') <> NVL(TO_CHAR(:NEW.CUSTOMNUMBER5),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CUSTOMNUMBER5';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CUSTOMNUMBER5;
v_rec.NEW_VALUE := :NEW.CUSTOMNUMBER5;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATE_DATE),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATE_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LAST_UPDATE_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATE_DATE;
v_rec.NEW_VALUE := :NEW.LAST_UPDATE_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATED_BY),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATED_BY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'LAST_UPDATED_BY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATED_BY;
v_rec.NEW_VALUE := :NEW.LAST_UPDATED_BY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CREATION_DATE),'X') <> NVL(TO_CHAR(:NEW.CREATION_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_REQUEST_ENTITY_COLUMNS';
v_rec.TABLE_COLUMN := 'CREATION_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CREATION_DATE;
v_rec.NEW_VALUE := :NEW.CREATION_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

EXCEPTION
when others then
apps.mt_log_error ( 'Audit Error - Table:  '||p_table_name||'ID: '|| :NEW.ID || ' exception ' || SQLERRM);
END;
/

