CREATE OR REPLACE TRIGGER XWRL_PARTY_MST_AFTER_IUD_TRG
AFTER INSERT OR UPDATE OR DELETE ON XWRL_PARTY_MASTER
FOR EACH ROW
DECLARE

cursor c1 is
select table_name, column_name
from all_tab_columns
where table_name = 'XWRL_PARTY_MASTER'
and data_type not in  ('XMLTYPE')
and column_name not in  ('SOAP_QUERY');

v_rec XWRL_AUDIT_LOG%rowtype;
p_row_action varchar2(20);
v_user_id  NUMBER  := apps.fnd_profile.value('USER_ID');
v_login_id NUMBER  := apps.fnd_profile.value('LOGIN_ID');
v_rec XWRL_AUDIT_LOG%rowtype;
v_rec.creation_date     := SYSDATE;
v_rec.last_update_date  := SYSDATE;
v_rec.last_updated_by   := v_user_id;
v_rec.created_by        := v_user_id;
v_rec.last_update_login := v_login_id;

BEGIN
IF INSERTING THEN 
p_row_action := 'INSERT';
ELSIF UPDATING THEN 
p_row_action := 'UPDATE';
ELSIF DELETING THEN 
p_row_action := 'DELETE';
END IF;

BEGIN
IF NVL(TO_CHAR(:OLD.TC_EXCLUDED),'X') <> NVL(TO_CHAR(:NEW.TC_EXCLUDED),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'TC_EXCLUDED';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.TC_EXCLUDED;
v_rec.NEW_VALUE := :NEW.TC_EXCLUDED;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.IDENTIFIER),'X') <> NVL(TO_CHAR(:NEW.IDENTIFIER),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'IDENTIFIER';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.IDENTIFIER;
v_rec.NEW_VALUE := :NEW.IDENTIFIER;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.NUMBER_OF_WORDS),'X') <> NVL(TO_CHAR(:NEW.NUMBER_OF_WORDS),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'NUMBER_OF_WORDS';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.NUMBER_OF_WORDS;
v_rec.NEW_VALUE := :NEW.NUMBER_OF_WORDS;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ID),'X') <> NVL(TO_CHAR(:NEW.ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ID;
v_rec.NEW_VALUE := :NEW.ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.WC_SCREENING_REQUEST_ID),'X') <> NVL(TO_CHAR(:NEW.WC_SCREENING_REQUEST_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'WC_SCREENING_REQUEST_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.WC_SCREENING_REQUEST_ID;
v_rec.NEW_VALUE := :NEW.WC_SCREENING_REQUEST_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.BATCH_ID),'X') <> NVL(TO_CHAR(:NEW.BATCH_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'BATCH_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.BATCH_ID;
v_rec.NEW_VALUE := :NEW.BATCH_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.RELATIONSHIP_TYPE),'X') <> NVL(TO_CHAR(:NEW.RELATIONSHIP_TYPE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'RELATIONSHIP_TYPE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.RELATIONSHIP_TYPE;
v_rec.NEW_VALUE := :NEW.RELATIONSHIP_TYPE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ENTITY_TYPE),'X') <> NVL(TO_CHAR(:NEW.ENTITY_TYPE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'ENTITY_TYPE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ENTITY_TYPE;
v_rec.NEW_VALUE := :NEW.ENTITY_TYPE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.STATE),'X') <> NVL(TO_CHAR(:NEW.STATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'STATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.STATE;
v_rec.NEW_VALUE := :NEW.STATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.STATUS),'X') <> NVL(TO_CHAR(:NEW.STATUS),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'STATUS';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.STATUS;
v_rec.NEW_VALUE := :NEW.STATUS;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SOURCE_TABLE),'X') <> NVL(TO_CHAR(:NEW.SOURCE_TABLE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SOURCE_TABLE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SOURCE_TABLE;
v_rec.NEW_VALUE := :NEW.SOURCE_TABLE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SOURCE_TABLE_COLUMN),'X') <> NVL(TO_CHAR(:NEW.SOURCE_TABLE_COLUMN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SOURCE_TABLE_COLUMN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SOURCE_TABLE_COLUMN;
v_rec.NEW_VALUE := :NEW.SOURCE_TABLE_COLUMN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SOURCE_ID),'X') <> NVL(TO_CHAR(:NEW.SOURCE_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SOURCE_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SOURCE_ID;
v_rec.NEW_VALUE := :NEW.SOURCE_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.XREF_SOURCE_TABLE),'X') <> NVL(TO_CHAR(:NEW.XREF_SOURCE_TABLE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'XREF_SOURCE_TABLE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.XREF_SOURCE_TABLE;
v_rec.NEW_VALUE := :NEW.XREF_SOURCE_TABLE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.XREF_SOURCE_TABLE_COLUMN),'X') <> NVL(TO_CHAR(:NEW.XREF_SOURCE_TABLE_COLUMN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'XREF_SOURCE_TABLE_COLUMN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.XREF_SOURCE_TABLE_COLUMN;
v_rec.NEW_VALUE := :NEW.XREF_SOURCE_TABLE_COLUMN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.XREF_SOURCE_ID),'X') <> NVL(TO_CHAR(:NEW.XREF_SOURCE_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'XREF_SOURCE_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.XREF_SOURCE_ID;
v_rec.NEW_VALUE := :NEW.XREF_SOURCE_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SOURCE_TARGET_COLUMN),'X') <> NVL(TO_CHAR(:NEW.SOURCE_TARGET_COLUMN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SOURCE_TARGET_COLUMN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SOURCE_TARGET_COLUMN;
v_rec.NEW_VALUE := :NEW.SOURCE_TARGET_COLUMN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.FULL_NAME),'X') <> NVL(TO_CHAR(:NEW.FULL_NAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'FULL_NAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.FULL_NAME;
v_rec.NEW_VALUE := :NEW.FULL_NAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.FAMILY_NAME),'X') <> NVL(TO_CHAR(:NEW.FAMILY_NAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'FAMILY_NAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.FAMILY_NAME;
v_rec.NEW_VALUE := :NEW.FAMILY_NAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.GIVEN_NAME),'X') <> NVL(TO_CHAR(:NEW.GIVEN_NAME),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'GIVEN_NAME';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.GIVEN_NAME;
v_rec.NEW_VALUE := :NEW.GIVEN_NAME;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.DATE_OF_BIRTH),'X') <> NVL(TO_CHAR(:NEW.DATE_OF_BIRTH),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'DATE_OF_BIRTH';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.DATE_OF_BIRTH;
v_rec.NEW_VALUE := :NEW.DATE_OF_BIRTH;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SEX),'X') <> NVL(TO_CHAR(:NEW.SEX),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SEX';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SEX;
v_rec.NEW_VALUE := :NEW.SEX;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.IMO_NUMBER),'X') <> NVL(TO_CHAR(:NEW.IMO_NUMBER),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'IMO_NUMBER';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.IMO_NUMBER;
v_rec.NEW_VALUE := :NEW.IMO_NUMBER;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.DEPARTMENT),'X') <> NVL(TO_CHAR(:NEW.DEPARTMENT),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'DEPARTMENT';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.DEPARTMENT;
v_rec.NEW_VALUE := :NEW.DEPARTMENT;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.OFFICE),'X') <> NVL(TO_CHAR(:NEW.OFFICE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'OFFICE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.OFFICE;
v_rec.NEW_VALUE := :NEW.OFFICE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.PRIORITY),'X') <> NVL(TO_CHAR(:NEW.PRIORITY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'PRIORITY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.PRIORITY;
v_rec.NEW_VALUE := :NEW.PRIORITY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.RISK_LEVEL),'X') <> NVL(TO_CHAR(:NEW.RISK_LEVEL),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'RISK_LEVEL';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.RISK_LEVEL;
v_rec.NEW_VALUE := :NEW.RISK_LEVEL;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.DOCUMENT_TYPE),'X') <> NVL(TO_CHAR(:NEW.DOCUMENT_TYPE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'DOCUMENT_TYPE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.DOCUMENT_TYPE;
v_rec.NEW_VALUE := :NEW.DOCUMENT_TYPE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CLOSED_DATE),'X') <> NVL(TO_CHAR(:NEW.CLOSED_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'CLOSED_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CLOSED_DATE;
v_rec.NEW_VALUE := :NEW.CLOSED_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.ASSIGNED_TO),'X') <> NVL(TO_CHAR(:NEW.ASSIGNED_TO),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'ASSIGNED_TO';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.ASSIGNED_TO;
v_rec.NEW_VALUE := :NEW.ASSIGNED_TO;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.VESSEL_INDICATOR),'X') <> NVL(TO_CHAR(:NEW.VESSEL_INDICATOR),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'VESSEL_INDICATOR';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.VESSEL_INDICATOR;
v_rec.NEW_VALUE := :NEW.VESSEL_INDICATOR;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.PASSPORT_NUMBER),'X') <> NVL(TO_CHAR(:NEW.PASSPORT_NUMBER),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'PASSPORT_NUMBER';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.PASSPORT_NUMBER;
v_rec.NEW_VALUE := :NEW.PASSPORT_NUMBER;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.PASSPORT_ISSUING_COUNTRY_CODE),'X') <> NVL(TO_CHAR(:NEW.PASSPORT_ISSUING_COUNTRY_CODE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'PASSPORT_ISSUING_COUNTRY_CODE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.PASSPORT_ISSUING_COUNTRY_CODE;
v_rec.NEW_VALUE := :NEW.PASSPORT_ISSUING_COUNTRY_CODE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CITIZENSHIP_COUNTRY_CODE),'X') <> NVL(TO_CHAR(:NEW.CITIZENSHIP_COUNTRY_CODE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'CITIZENSHIP_COUNTRY_CODE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CITIZENSHIP_COUNTRY_CODE;
v_rec.NEW_VALUE := :NEW.CITIZENSHIP_COUNTRY_CODE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.COUNTRY_OF_RESIDENCE),'X') <> NVL(TO_CHAR(:NEW.COUNTRY_OF_RESIDENCE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'COUNTRY_OF_RESIDENCE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.COUNTRY_OF_RESIDENCE;
v_rec.NEW_VALUE := :NEW.COUNTRY_OF_RESIDENCE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CITY_OF_RESIDENCE_ID),'X') <> NVL(TO_CHAR(:NEW.CITY_OF_RESIDENCE_ID),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'CITY_OF_RESIDENCE_ID';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CITY_OF_RESIDENCE_ID;
v_rec.NEW_VALUE := :NEW.CITY_OF_RESIDENCE_ID;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.NOTE),'X') <> NVL(TO_CHAR(:NEW.NOTE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'NOTE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.NOTE;
v_rec.NEW_VALUE := :NEW.NOTE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.START_DATE),'X') <> NVL(TO_CHAR(:NEW.START_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'START_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.START_DATE;
v_rec.NEW_VALUE := :NEW.START_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.END_DATE),'X') <> NVL(TO_CHAR(:NEW.END_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'END_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.END_DATE;
v_rec.NEW_VALUE := :NEW.END_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATE_DATE),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATE_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'LAST_UPDATE_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATE_DATE;
v_rec.NEW_VALUE := :NEW.LAST_UPDATE_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATED_BY),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATED_BY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'LAST_UPDATED_BY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATED_BY;
v_rec.NEW_VALUE := :NEW.LAST_UPDATED_BY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CREATION_DATE),'X') <> NVL(TO_CHAR(:NEW.CREATION_DATE),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'CREATION_DATE';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CREATION_DATE;
v_rec.NEW_VALUE := :NEW.CREATION_DATE;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.CREATED_BY),'X') <> NVL(TO_CHAR(:NEW.CREATED_BY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'CREATED_BY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.CREATED_BY;
v_rec.NEW_VALUE := :NEW.CREATED_BY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.LAST_UPDATE_LOGIN),'X') <> NVL(TO_CHAR(:NEW.LAST_UPDATE_LOGIN),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'LAST_UPDATE_LOGIN';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.LAST_UPDATE_LOGIN;
v_rec.NEW_VALUE := :NEW.LAST_UPDATE_LOGIN;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.SOURCE_KEY),'X') <> NVL(TO_CHAR(:NEW.SOURCE_KEY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'SOURCE_KEY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.SOURCE_KEY;
v_rec.NEW_VALUE := :NEW.SOURCE_KEY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

BEGIN
IF NVL(TO_CHAR(:OLD.XREF_SOURCE_KEY),'X') <> NVL(TO_CHAR(:NEW.XREF_SOURCE_KEY),'X')  THEN 
IF p_row_action = 'DELETE' THEN 
v_rec.TABLE_ID := :OLD.ID;
ELSE
v_rec.TABLE_ID := :NEW.ID;
END IF;
v_rec.TABLE_NAME := 'XWRL_PARTY_MASTER';
v_rec.TABLE_COLUMN := 'XREF_SOURCE_KEY';
v_rec.ROW_ACTION :=  p_row_action;
v_rec.OLD_VALUE := :OLD.XREF_SOURCE_KEY;
v_rec.NEW_VALUE := :NEW.XREF_SOURCE_KEY;
INSERT INTO XWRL_AUDIT_LOG values v_rec;
END IF;
END;

EXCEPTION
when others then
apps.mt_log_error ( 'Audit Error - Table:  '||p_table_name||'ID: '|| :NEW.ID || ' exception ' || SQLERRM);
END;
/

