
  CREATE OR REPLACE EDITIONABLE TRIGGER "XWRL"."XWRL_REQUEST_ROWS_TRG" BEFORE
   INSERT ON xwrl_request_rows
   FOR EACH ROW
BEGIN
   IF (:new.id IS NULL) THEN
      :new.id := xwrl_requests3_seq.nextval;
   END IF;
END;
/
ALTER TRIGGER "XWRL"."XWRL_REQUEST_ROWS_TRG" ENABLE
;
