
  CREATE OR REPLACE EDITIONABLE TRIGGER "XWRL"."XWRL_REQUESTS" BEFORE
   INSERT ON xwrl_requests
   FOR EACH ROW
BEGIN

   IF (:new.id IS NULL) THEN
      :new.id := xwrl_requests_seq.nextval;
   END IF;

END;
/
ALTER TRIGGER "XWRL"."XWRL_REQUESTS" ENABLE
;
