ALTER TABLE xwrl.XWRL_REQUESTS add (compressed_request                         XMLTYPE);

ALTER TABLE xwrl.XWRL_REQUESTS drop (compressed_request                  );


 insert  into "XWRL"."XWRL_PARAMETERS" (ID, KEY, VALUE_STRING) VALUES ('XML', 'COMPRESSED_XML', 'FALSE');

SELECT * 
FROM XWRL_PARAMETERS
WHERE ID = 'XML'
AND key = 'COMPRESSED_XML'
;

UPDATE XWRL_PARAMETERS
SET VALUE_STRING = 'TRUE'
WHERE ID = 'XML'
AND key = 'COMPRESSED_XML';

UPDATE XWRL_PARAMETERS
SET VALUE_STRING = 'FALSE'
WHERE ID = 'XML'
AND key = 'COMPRESSED_XML';
