package com.rmi.login.adfbc.services;

import com.rmi.login.adfbc.services.common.RmiLoginAppModule;

import com.rmi.login.adfbc.utils.AdfUtils;

import com.rmi.login.adfbc.utils.RmiPasswordEncryptorModel;

import java.io.IOException;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import javax.servlet.http.HttpSession;
import javax.servlet.ServletException;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import weblogic.servlet.security.ServletAuthentication;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 30 07:46:32 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RmiLoginAppModuleImpl extends ApplicationModuleImpl implements RmiLoginAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public RmiLoginAppModuleImpl() {
    }

    /**
     * Container's getter for RmiUserLoginView.
     * @return RmiUserLoginView
     */
    public ViewObjectImpl getRmiUserLoginView() {
        return (ViewObjectImpl) findViewObject("RmiUserLoginView");
    }

    /**
     * Method fetches user details of the login user.
     * @param username pass username of logged in user
     * @return Row returns filtered row from the UserDetails1 VO.
     **/
    public Row getUserDetails(String userName)
    {
        Row row = null;
        try {
            ViewObjectImpl rmiUserLoginView = getRmiUserLoginView();
            rmiUserLoginView.setNamedWhereClauseParam("pUserName", userName);
            rmiUserLoginView.executeQuery();
            row = rmiUserLoginView.first();
        } catch (Exception e) {
            e.printStackTrace();
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while validating password. Please contact your System Administrator.",
                                          "", FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }
    
    /**
     * Method fetches user details of the login user in the FND_USER table.
     * @param pUserId pass User Id of logged in user
     * @return Row returns filtered row from the UserFndDetails VO.
     **/
    public Row getUserRmiDetails(Integer pUserId) {
        Row row = null;
        try {
            ViewObjectImpl fndUserLoginView = getUserFndDetailsView();
            fndUserLoginView.setNamedWhereClauseParam("pUserId", pUserId);
            fndUserLoginView.executeQuery();
            row = fndUserLoginView.first();
        } catch (Exception e) {
            e.printStackTrace();
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while validating password. Please contact your System Administrator.",
                                                   "", FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }

    /**
     * Method is used to send email notification to user.
     * @param to - pass receiver of the email
     * @param cc - pass cc receiver(s) of the email
     * @param bcc - pass cc receiver(s) of the email
     * @param subject - pass subject of the email
     * @param body - pass body of the email
     **/

    public void sendMail(String to, String cc, String bcc, String subject, String body) {
        CallableStatement st = null;
        try {
            String sql = "BEGIN rmi_sicd_pub.sendmail_notif_proc(?,?,?,?,?,?,?,?);END;";
            st = getDBTransaction().createCallableStatement(sql, 0);
            st.setObject(1, "exch-03.iri.int"); //MAIL SERVER
            st.setObject(2, "no-reply@register-iri.com"); //SENDER
            st.setObject(3, to); //TO
            st.setObject(4, cc); //CC
            st.setObject(5, bcc); //BCC
            st.setObject(6, subject); //SUBJECT
            st.setObject(7, body); //BODY
            st.registerOutParameter(8, Types.VARCHAR); //OUT PARAM ERROR
            st.execute();
        } catch (SQLException e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while sending email notification !",
                                                   "", FacesMessage.SEVERITY_ERROR);
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                    AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while sending email notification !", "",
                                                  FacesMessage.SEVERITY_ERROR);
                }
            }
        }
    }

    /**
     * Method fetches the menu(s) assigned to the login user of different roles.
     * @param userId - pass userId of logged in user
     * @param roleId - pass roleId of current user (can be null).
     **/
    public void menuOnLoad(String userId) {
        try {
            getUserMenuView().setNamedWhereClauseParam("pUserId", Integer.parseInt(userId));
            getUserMenuView().executeQuery();
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while fetching menu on load !", "",
                                          FacesMessage.SEVERITY_ERROR);
        }
    }

    /**
     * Method fetches role(s) assigned to the login user.
     * @param userId - pass userId of logged in user
     * @param roleId - pass roleId of current user (can be null).
     * @return Row.
     **/
    public Row getRoleDetails(String userId) {
        Row row = null;
        try {
            if(userId != null)
            {
                getRolesView().setNamedWhereClauseParam("pUserId", Integer.parseInt(userId));
                getRolesView().executeQuery();
                row = getRolesView().first();    
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while fetching user details !", "",
                                          FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }

    /**
     * Method fetches single role details assigned to the login user.
     * @param userId - pass userId of logged in user
     * @param roleId - pass roleId of current user (can be null).
     * @return Row.
     **/
    public Row getSingleRoleDetails(String userId, BigDecimal roleId) {
        Row row = null;
        try {
            if(userId != null && roleId != null)
            {
                getRolesView().setNamedWhereClauseParam("pUserId", userId);
                getRolesView().setNamedWhereClauseParam("pRoleId", roleId);
                getRolesView().executeQuery();
                row = getRolesView().first();   
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while fetching role details !", "",
                                          FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }

    public Row getMenuItems(String taskflowId, String roleId) {
        Row row = null;
        try {
            getMenuItemView().setNamedWhereClauseParam("pTaskflowId", taskflowId);
            getMenuItemView().setNamedWhereClauseParam("pRoleId", roleId);
            getMenuItemView().executeQuery();
            row = getMenuItemView().first();
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while fetching user details !", "",
                                          FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }

    /**
     * Method changes password of login user.
     * @param userName - pass userName of logged in user
     * @param password - pass new password.
     **/
    public void changePassword(String userName, String password) {
        try {
            getRmiUserView().setNamedWhereClauseParam("pUserName", userName);
            getRmiUserView().executeQuery();
            Row row = getRmiUserView().first();
            row.setAttribute("Password", password);
            row.setAttribute("Status", "A");
            row.setAttribute("PasswordUpdationDate", new Timestamp(System.currentTimeMillis()));
            
            ViewObjectImpl pwdHistVo = this.getRmiUserPasswordHistoryView1();
            pwdHistVo.setNamedWhereClauseParam("pUserId", row.getAttribute("UserId"));
            pwdHistVo.executeQuery();

            RowSetIterator usrPwdHistRsi = pwdHistVo.createRowSetIterator(null);
            Row usrPwdHistRow = null;

            while (usrPwdHistRsi.hasNext()) 
            {
                Row r = usrPwdHistRsi.next();

                if (r != null && r.getAttribute("PasswordRepetitionCount") != null
                    && r.getAttribute("Password") != null) 
                {
                    r.setAttribute("PasswordRepetitionCount", Integer.parseInt(r.getAttribute("PasswordRepetitionCount").toString()) + 1);
                    if(RmiPasswordEncryptorModel.Decrypt(r.getAttribute("Password").toString()).equalsIgnoreCase(RmiPasswordEncryptorModel.Decrypt(password)))
                        usrPwdHistRow = r;
                }
            }
            usrPwdHistRsi.closeRowSetIterator();
            
            if(usrPwdHistRow != null)
            {
                usrPwdHistRow.setAttribute("PasswordRepetitionCount", new BigDecimal(0));
            }
            else
            {
                usrPwdHistRow = this.getRmiUserPasswordHistoryView1().createRow();
                usrPwdHistRow.setAttribute("UserId", row.getAttribute("UserId"));
                usrPwdHistRow.setAttribute("Password", password);
                usrPwdHistRow.setAttribute("PasswordUpdationDate", new Timestamp(System.currentTimeMillis()));
                usrPwdHistRow.setAttribute("PasswordRepetitionCount", new BigDecimal(0));
                this.getRmiUserPasswordHistoryView1().insertRow(usrPwdHistRow);
            }
            
            this.getDBTransaction().commit();
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception during password change. Please contact your System Administrator.",
                                          "", FacesMessage.SEVERITY_ERROR);
        }
    }

    /**
     * Method resets new password for login user.
     * @param userName - pass userName of logged in user
     * @param resetPassword - pass new generated password.
     **/
    public void setResetPassword(String userName, String resetPassword) {
        try {
            getRmiUserView().setNamedWhereClauseParam("pUserName", userName);
            getRmiUserView().executeQuery();
            Row row = getRmiUserView().first();
            row.setAttribute("ResetPassword", resetPassword);
            row.setAttribute("Password", resetPassword);
            row.setAttribute("Status", "P");
            this.getDBTransaction().commit();
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while using ‘Forgot Password’. Please contact your System Administrator.",
                                          "", FacesMessage.SEVERITY_ERROR);
        }
    }

    /**
     * Method fetches email body for selected email type.
     * @param emailType - pass email type i.e. OTP/Reset.
     * @return Row.
     **/
    public Row getEmailNotifBody(String emailType) {
        Row row = null;
        try {
            getRmiEmailNotifBodyView().setNamedWhereClauseParam("pEmailType", emailType);
            getRmiEmailNotifBodyView().executeQuery();
            row = getRmiEmailNotifBodyView().first();
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while fetching user details. Please contact your System Administrator.", "",
                                          FacesMessage.SEVERITY_ERROR);
        }
        return row;
    }
    
    /**
     *  Method validates user old password repetition validation (after 7 times).
     *  @param password pass entered password which is to be validated.
     *  @param userName pass username for which the password is to be validated.
     *  @return String returns Y/N - Success/Failed.
     **/
    public String validatePasswordHistory(String password, String userName)
    {
        try 
        {
            if (password != null && password != null) {
                Row userRow = getUserDetails(userName.toUpperCase());

                if (userRow != null && userRow.getAttribute("UserId") != null) {
                    ViewObjectImpl pwdHistVo = this.getRmiUserPasswordHistoryView1();
                    pwdHistVo.setNamedWhereClauseParam("pUserId", userRow.getAttribute("UserId"));
                    pwdHistVo.executeQuery();

                    Row[] usrPwdHistRows = pwdHistVo.getAllRowsInRange();

                    if (usrPwdHistRows.length > 0) {
                        RowSetIterator usrPwdHistRsi = pwdHistVo.createRowSetIterator(null);

                        while (usrPwdHistRsi.hasNext()) {
                            Row r = usrPwdHistRsi.next();

                            if (r != null && r.getAttribute("Password") != null) {
                                if (RmiPasswordEncryptorModel.Decrypt(r.getAttribute("Password").toString()).equalsIgnoreCase(password) &&
                                    Integer.parseInt(r.getAttribute("PasswordRepetitionCount").toString()) < 7)
                                    return "N";
                            }
                        }
                        usrPwdHistRsi.closeRowSetIterator();
                    }
                }
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while validating user password history." +
                                                   "Please contact your System Administrator.", "",
                                                   FacesMessage.SEVERITY_ERROR);
        }
        
        return "Y";
    }
    
    /**
     *    Method updates User last login time in database for given username. 
     *    @param userName, pass username for which you want to update the last login time.
     **/
    public void updateUserLoginTime(String userName)
    {        
        try 
        {
            if (userName != null) {
                getRmiUserView().setNamedWhereClauseParam("pUserName", userName);
                getRmiUserView().executeQuery();
                Row row = getRmiUserView().first();
                row.setAttribute("UserLoginTime", new Timestamp(System.currentTimeMillis()));
                //            System.out.println("UserLoginTime :: "+row.getAttribute("UserLoginTime"));
                //            row.setAttribute("OtpEndTime", ((row.getAttribute("UserType") != null && row.getAttribute("UserType").toString().equalsIgnoreCase("External")))
                //                                            ? new Timestamp(System.currentTimeMillis())
                //                                            : null);

                this.getDBTransaction().commit();
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while updating user last login time in database." +
                                                   "Please contact your System Administrator.", "",
                                                   FacesMessage.SEVERITY_ERROR);
        }
    }
    
    /**
     *    Method updates User otp start/end times in database for given username. 
     *    @param userName, pass username for which you want to update the otp times.
     **/
    public void updateOtpTime(String userName)
    {
        try 
        {
            if (userName != null) {
                getRmiUserView().setNamedWhereClauseParam("pUserName", userName);
                getRmiUserView().executeQuery();
                Row row = getRmiUserView().first();
                row.setAttribute("OtpStartTime", new Timestamp(System.currentTimeMillis()));
                row.setAttribute("OtpEndTime",
                                 new Timestamp(System.currentTimeMillis() + TimeUnit.MINUTES.toMillis(10)));
                this.getDBTransaction().commit();
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while updating OTP time in database." +
                                                   "Please contact your System Administrator.", "",
                                                   FacesMessage.SEVERITY_ERROR);
        }
    }
    
    /**
     *    Method calculates and refreshes User otp remaining time from the given time on screen. 
     *    @param otpEndTime, pass otp end time from which the system calculates remaining time.
     **/
    public void refreshOtpEndTime(Timestamp otpEndTime)
    {
        try 
        {
            if (otpEndTime != null) {
                String[] actualTime = otpEndTime.toString().split("\\.");

                if (actualTime.length > 0 && actualTime[0] != null) {
                    //                System.out.println("actual time :: "+actualTime[0]);
                    ViewObjectImpl otpTimerView = this.getOtpTimerView1();
                    otpTimerView.setNamedWhereClauseParam("pOtpEndTime", actualTime[0]);
                    otpTimerView.executeQuery();
                }
            }
        } catch (Exception e) {
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while refreshing OTP timer." +
                                                   "Please contact your System Administrator.", "",
                                                   FacesMessage.SEVERITY_ERROR);
        }
    }
    
    /**
     *    Method validates the session and redirects the URL to Login page.
     **/
    public void applicationHomeRedirect() 
    {
        try 
        {
            System.out.println("applicationHomeRedirect called");
            FacesContext fctx = null;
            HttpServletRequest request = null;
            HttpServletResponse response = null;
            ExternalContext ectx = null;
            String url = null;

            fctx = FacesContext.getCurrentInstance();
            
            if(fctx != null)
            {
                ectx = fctx.getExternalContext();
                url = ectx.getRequestContextPath() + "/seaf/Login";
            }
            request = (HttpServletRequest) fctx.getExternalContext().getRequest();
            response = (HttpServletResponse) fctx.getExternalContext().getResponse();
            
            try {
                HttpSession session = (HttpSession) ectx.getSession(false);
                session.invalidate();
                request.logout();
                ServletAuthentication.invalidateAll(request);
                ServletAuthentication.killCookie(request);
            } catch (Exception e) {
                e.printStackTrace();
            }           
            
            System.out.println("url :: "+url);
//            response.sendRedirect(url);
            
        }catch (Exception e) {
            e.printStackTrace();
            AdfUtils.addFormattedFacesErrorMessage("System encountered an exception while redirecting." +
                                                   "Please contact your System Administrator.", "",
                                                   FacesMessage.SEVERITY_ERROR);
        }
    }
    
    /**
     * Container's getter for UserMenuView1.
     * @return UserMenuView1
     */
    public ViewObjectImpl getUserMenuView() {
        return (ViewObjectImpl) findViewObject("UserMenuView");
    }

    /**
     * Container's getter for UserSubMenuView1.
     * @return UserSubMenuView1
     */
    public ViewObjectImpl getUserSubMenuView() {
        return (ViewObjectImpl) findViewObject("UserSubMenuView");
    }

    /**
     * Container's getter for MenuSubMenuLink1.
     * @return MenuSubMenuLink1
     */
    public ViewLinkImpl getMenuSubMenuLink() {
        return (ViewLinkImpl) findViewLink("MenuSubMenuLink");
    }

    /**
     * Container's getter for RolesView1.
     * @return RolesView1
     */
    public ViewObjectImpl getRolesView() {
        return (ViewObjectImpl) findViewObject("RolesView");
    }

    /**
     * Container's getter for MenuItemView1.
     * @return MenuItemView1
     */
    public ViewObjectImpl getMenuItemView() {
        return (ViewObjectImpl) findViewObject("MenuItemView");
    }

    /**
     * Container's getter for RmiUserView1.
     * @return RmiUserView1
     */
    public ViewObjectImpl getRmiUserView() {
        return (ViewObjectImpl) findViewObject("RmiUserView");
    }

    /**
     * Container's getter for RmiEmailNotifBodyView1.
     * @return RmiEmailNotifBodyView1
     */
    public ViewObjectImpl getRmiEmailNotifBodyView() {
        return (ViewObjectImpl) findViewObject("RmiEmailNotifBodyView");
    }

    /**
     * Container's getter for UserFndDetailsView1.
     * @return UserFndDetailsView1
     */
    public ViewObjectImpl getUserFndDetailsView() {
        return (ViewObjectImpl) findViewObject("UserFndDetailsView");
    }

    /**
     * Container's getter for RmiUserPasswordHistoryView1.
     * @return RmiUserPasswordHistoryView1
     */
    public ViewObjectImpl getRmiUserPasswordHistoryView1() {
        return (ViewObjectImpl) findViewObject("RmiUserPasswordHistoryView1");
    }

    /**
     * Container's getter for OtpTimerView1.
     * @return OtpTimerView1
     */
    public ViewObjectImpl getOtpTimerView1() {
        return (ViewObjectImpl) findViewObject("OtpTimerView1");
    }
}

